### ISSUE TITLE
Handle cases where a URLStreamHandlerFactory is already installed [PAXRUNNER-85]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#107]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** created **[PAXRUNNER-85](https://ops4j1.jira.com/browse/PAXRUNNER-85)** 

As reported by Hendy: when provisioning using NetBeans, an exception occurs because NB has already installed its own URLStreamHandlerFactory:

java.lang.Error: factory already defined<br /> at java.net.URL.setURLStreamHandlerFactory(URL.java:1076)<br /> at org.ops4j.pax.runner.handler.internal.URLStreamHandlerExtender.start (URLStreamHandlerExtender.java:67)<br /> at org.ops4j.pax.runner.handler.internal.Activator.start(Activator.java:66)<br /> at org.ops4j.pax.runner.Run.createActivator(Run.java:405)<br /> at org.ops4j.pax.runner.Run.installHandlers (Run.java:175)<br /> at org.ops4j.pax.runner.Run.start(Run.java:134)<br /> at org.ops4j.pax.runner.Run.main(Run.java:481)

Quick fix is to catch this exception and simply continue (although this will definitely limit the available functionality) - a better solution, which is used in several applications, is to use reflection to forcibly update the URLStreamHandlerFactory with the Pax-Runner factory and delegate to the original factory for unknown protocols...

---

**Affects:** 0.5.5
**Fixed in:** 0.5.6
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

BTW, because we don't know the name of the field where the factory is kept (it's implementation specific) we would need to loop over the fields in the URL class and look for ones with type URLStreamHandlerFactory - seems a bit hacky but it's the only viable workaround that I'm aware of.

**Comment by ops4j-issues** [comment]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** commented

Setting up NetBeans to use external maven "solves" the problem:



i can setup netbeans to use external maven:



1. Tools - Options - Miscellaneous - Maven 2. Setup Maven Home directory.<br /> 2. Project properties -&gt; Actions -&gt; Use external Maven



This basically loses capability for debugging. :question:



I think pax-construct-generated maven project has not so perfect NetBeans project support initially too :slightly_frowning_face:

**Comment by ops4j-issues** [comment]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** commented

From the user standpoint, pax-runner is a replacement of Equinox/Felix so they expect it to behave at least as easy (and not more troublesome) than these engines.



I can run Equinox directly from NetBeans so it's pretty unfortunate that I can't run pax-runner directly.



Maybe it's better to have it as a warning (ie. "WARNING: can't install url stream factory... some features disabled") but the app still continues.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Related to your remark about the Warning: this cannot be done as the url setting/handling is core for pax runner. So, f I do not set the url stream handler factory you would not be able to use the mvn: urls' (just the standard ones (file/http/zip)



But, I implemented as explained by Stuart above and I think this will solve your case, so please give it a try.<br /> Yet, is not 100% solved correctly as I do set but I do not reset back to the original handler, so this may cause unforeseen problems (I still delegate to the original handler but after runner stops the factory remains set).



This case (reset) will be solved in a more generic way as I plan to implement a shutdown phase of the frameworks/runner (right now I just kill the launched framework and exit)

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Confirmed that works by Hendy.
