### ISSUE TITLE
Space in bundle url not handled correctly in Concierge startup file [PAXRUNNER-92]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#112]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXRUNNER-92](https://ops4j1.jira.com/browse/PAXRUNNER-92)** 

When the path to pax runner working directory contains spaces Concierge will interpret the space as a separator between bundles to be installed as reported by Cameron Taggart:

Pax Runner from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> --------------------------------------------

-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties) <br /> -&gt; Downloading bundles...<br /> -&gt; Execution environment [J2SE-1.6](https://ops4j1.jira.com/wiki/display/paxrunner/J2SE-1.6)<br /> -&gt; Starting platform [Concierge 1.0.0](https://ops4j1.jira.com/wiki/display/paxrunner/Concierge+1.0.0). Runner has succesfully finished his job!<br /> --------------------------------------------------------- <br /> Concierge OSGi 1.0_RC1 on Windows XP 5.1 starting ...<br /> ---------------------------------------------------------<br /> purging storage ...<br /> IGNORING NON-BUNDLE [file:/D:/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/Concierge](file:/D:/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/Concierge) <br /> IGNORING NON-BUNDLE via<br /> INSTALLING Pax/runner/bundles/1243266899.jar<br /> IGNORING NON-BUNDLE [file:/D:/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/Concierge](file:/D:/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/Concierge)<br /> IGNORING NON-BUNDLE via<br /> INSTALLING Pax/runner/bundles/2049110755.jar <br /> org.osgi.framework.BundleException: Cannot retrieve bundle from Pax/runner/bundles/1243266899.jar<br /> at ch.ethz.iks.concierge.framework.Framework.installNewBundle(Framework.java:1059)<br /> at ch.ethz.iks.concierge.framework.Framework.startup (Framework.java:457)<br /> at ch.ethz.iks.concierge.framework.Framework.main(Framework.java:314)<br /> java.io.FileNotFoundException: D:\eclipse\workspace\.metadata\.plugins\org.eclipse.pde.core\Concierge via Pax\runner\concierge\Pax\runner\bundles\1243266899.jar (The system cannot find the path specified) <br /> at java.io.FileInputStream.open(Native Method)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)<br /> at sun.net.www.protocol.file.FileURLConnection.connect (FileURLConnection.java:70)<br /> at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:161)<br /> at ch.ethz.iks.concierge.framework.Framework.installNewBundle(Framework.java:1056)<br /> at ch.ethz.iks.concierge.framework.Framework.startup(Framework.java:457)<br /> at ch.ethz.iks.concierge.framework.Framework.main(Framework.java:314)<br /> org.osgi.framework.BundleException: Cannot retrieve bundle from Pax/runner/bundles/2049110755.jar <br /> at ch.ethz.iks.concierge.framework.Framework.installNewBundle(Framework.java:1059)<br /> at ch.ethz.iks.concierge.framework.Framework.startup(Framework.java:457)<br /> at ch.ethz.iks.concierge.framework.Framework.main (Framework.java:314)<br /> java.io.FileNotFoundException: D:\eclipse\workspace\.metadata\.plugins\org.eclipse.pde.core\Concierge via Pax\runner\concierge\Pax\runner\bundles\2049110755.jar (The system cannot find the path specified) <br /> at java.io.FileInputStream.open(Native Method)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)<br /> at sun.net.www.protocol.file.FileURLConnection.connect (FileURLConnection.java:70)<br /> at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:161)<br /> at ch.ethz.iks.concierge.framework.Framework.installNewBundle(Framework.java:1056)<br /> at ch.ethz.iks.concierge.framework.Framework.startup(Framework.java:457)<br /> at ch.ethz.iks.concierge.framework.Framework.main(Framework.java:314)<br /> ---------------------------------------------------------<br /> Framework started in 0.891 seconds.<br /> ---------------------------------------------------------

---

**Affects:** 0.5.6
**Fixed in:** 0.6.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

I tested eclipse/felix/knopflerfish for this kind of issue and they run okay.
