### ISSUE TITLE
Runner tries to start a fragment bundle using Knopflerfish [PAXRUNNER-125]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#146]
**[DamianG](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2092aae3-b49e-4a62-814c-9b1b9e537a8c)** created **[PAXRUNNER-125](https://ops4j1.jira.com/browse/PAXRUNNER-125)** 

While starting my app using Knopflerfish I've got:

org.osgi.framework.BundleException: Cannot start a fragment bundle<br /> at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:299)<br /> at org.knopflerfish.framework.Framework.startBundle(Framework.java:501)<br /> at org.knopflerfish.framework.Main.handleArgs(Main.java:275)<br /> at org.knopflerfish.framework.Main.main(Main.java:192)<br /> Error: Command "-istart [file:/c:/Temp/cpc-runner/runner/bundles/compass_spring_0.0.2.SNAPSHOT.jar](file:/c:/Temp/cpc-runner/runner/bundles/compass_spring_0.0.2.SNAPSHOT.jar)" failed, Cannot start a fragment bundle<br /> -&gt; Shuting down platform...<br /> -&gt; Destroying platform process...

compass_spring bundle is a fragment, so I suppose it should be used "-install" instead of "-istart"

---

**Fixed in:** (none)
Votes: 3, Watches: 1

**Comment by ops4j-issues** [comment]
**[DamianG](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:2092aae3-b49e-4a62-814c-9b1b9e537a8c)** commented

Workaround:<br /> add `@nostart` in bundle url w bundles.txt

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

As in all of this time there was no more interest in this issue I'm closing it till further interest.

**Comment by ops4j-issues** [comment]
**[(unknown user)](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e5886e24-83d6-4a23-b7a9-3622790d8d79)** commented

Knopflerfish handles this differently from Felix and Equinox. Since a fragment cannot be started, the framework should not attempt to do so.

**Comment by ops4j-issues** [comment]
**[Matt Bishop](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:14c6c988-e76e-4234-8c2f-54b6ecf84eef)** commented

Alin, it is hard to interpret your close comment positively. Pax Runner has stated support for knopplerfish; this bug should be fixed so that the knopplerfish platform is supported. You don't need a pile of votes or comments to fix it.



If you don't believe anyone is interested in knopplerfish then please remove it as a platform that pax runner supports.

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

Hi Matt, thanks for heads up.<br /> OPS4J is about open participation. You can grab the source and commit the fix yourself. It does not need a "pile of votes" .. :wink:

**Comment by ops4j-issues** [comment]
**[Tuomas Kiviaho](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:1b9f7ab9-5a53-423a-bed4-4780828202e5)** commented

Same thing with Felix except that config.ini contains felix.auto.start instead of felix.auto.install. I'm using an older 4.0.2 version so this might not be an issue with newer ones.
