### ISSUE TITLE
java.lang.Enum dependency in pax-runner_1.4.0 for jdk1.4 [PAXRUNNER-330]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#147]
**[Tom Kesling](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:111b95e9-f30d-47ea-94b4-fee88de3afe3)** created **[PAXRUNNER-330](https://ops4j1.jira.com/browse/PAXRUNNER-330)** 

Trying to execute pax-run-1.4.bat throws exception below. Seems there may be a dependency on java 1.5<br /> Exception caught during execution:<br /> java.lang.NoClassDefFoundError: java/lang/Enum<br /> at java.lang.ClassLoader.defineClass0(Native Method)<br /> at java.lang.ClassLoader.defineClass(Unknown Source)<br /> at java.security.SecureClassLoader.defineClass(Unknown Source)<br /> at java.net.URLClassLoader.defineClass(Unknown Source)<br /> at java.net.URLClassLoader.access$100(Unknown Source)<br /> at java.net.URLClassLoader$1.run(Unknown Source)<br /> at java.security.AccessController.doPrivileged(Native Method)<br /> at java.net.URLClassLoader.findClass(Unknown Source)<br /> at java.lang.ClassLoader.loadClass(Unknown Source)<br /> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)<br /> at java.lang.ClassLoader.loadClass(Unknown Source)<br /> at java.lang.ClassLoader.loadClassInternal(Unknown Source)<br /> at org.ops4j.pax.runner.Run.initializeLogger(Run.java:846)<br /> at org.ops4j.pax.runner.Run.main(Run.java:140)<br /> at org.ops4j.pax.runner.Run.main(Run.java:120)

---

**Affects:** 1.4.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Niclas Hedhman](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:77912594-0a3e-4553-bb52-9b876d71537e)** commented

Yes. The Pax Runner Core has a Java 5 dependency.



I am not sure if the 1.4 support was officially decided on, or just an experiment to see if we can get it going. Initially, Pax Runner was Java 5 only, and by now 1.4 is way past End-of-Life, so not sure if this has priority or not.

**Comment by ops4j-issues** [comment]
**[MarcelM](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a7b1a3a0-3dd1-4bab-85a4-26e70be02bf6)** commented

Both 1.4 and Java 5 have been end of lifed on the desktop, so from that point of view I would not bother.



However, if you look at OSGi and most frameworks being able to run on other execution environments, there is at least a reason to support that. We're mainly talking embedded environments here. On the other hand, I feel Pax Runner was not really designed as a framework runner for those environments (I'm referring to the fact that Runner always downloads frameworks from the net instead of having options to embed them somehow).



So the real question here is, does Runner try to cover the embedded uses of OSGi?
