### ISSUE TITLE
Provide a way to start OSGi framework using an external Java runner service [PAXRUNNER-127]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#148]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** created **[PAXRUNNER-127](https://ops4j1.jira.com/browse/PAXRUNNER-127)** 

Currently Pax-Runner doesn't work well in Eclipse debug mode, because the process being debugged is the launching process not the OSGi framework. Eclipse does support tracking and debugging of additional processes, but this requires improving Pax-Runner to support starting the OSGi framework as daemon process (no waitFor) and returning the started Process through the Pax-Runner API.

---

**Affects:** 0.7.2
**Fixed in:** 0.8.0
**Attachments:**
* [Picture 2.png](https://ops4j1.jira.com/secure/attachment/10142/Picture 2.png)

Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Fixed in trunk, will open new issue to update Pax-Cursor to use new API methods.

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Reworking to fully support Eclipse debugging

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Stuart,



After the last changes I saw that once the framework is tarted if you hit Ctrl+C, there are a lot of exception as bellow. Please check that out also.<br /> java.io.IOException: Stream closed<br /> at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:145)<br /> at java.io.BufferedInputStream.read(BufferedInputStream.java:304)<br /> at org.ops4j.pax.runner.platform.internal.Pipe.run(Pipe.java:95)<br /> at java.lang.Thread.run(Thread.java:613)

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Committed reworked API to trunk

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

Hi Alin - could you try the latest commit? (as of a few minutes ago) ... if the exception still occurs, I'll need to know the OS and JVM version involved - as well as whether it was invoked from Eclipse or the command line.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Still the same.<br /> Mac OS X Leopard<br /> java version "1.5.0_13"<br /> Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_13-b05-237)<br /> Java HotSpot(TM) Client VM (build 1.5.0_13-119, mixed mode, sharing)



from command line. I know for sure that worked before as that's my way to get out as I hate typing exit of shutdown :smile:

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

OK - try it now, it appears to only occur on multi-core systems and was related to the ordering between stopping pipes and killing the process (exceptions in the pipes are ignored once they're marked as stopped, so they should be stopped before the process is killed as it used to be - this ordering was reversed during recent refactoring, so I just swapped it back)

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Pipes exceptions are gone. Solved.
