### ISSUE TITLE
Felix 1.0.1 fails to start [PAXRUNNER-190]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#224]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXRUNNER-190](https://ops4j1.jira.com/browse/PAXRUNNER-190)** 

Felix 1.0.1 cannot be started. It fails with the following exception:<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: Invalid platform definition<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: Invalid platform definition<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:537)<br /> at org.ops4j.pax.runner.Run.start(Run.java:201)<br /> at org.ops4j.pax.runner.Run.main(Run.java:129)<br /> at org.ops4j.pax.runner.Run.main(Run.java:102)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException: Invalid platform definition<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.createPlatformDefinition(PlatformImpl.java:775)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:127)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:533)<br /> ... 3 more<br /> Caused by: org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.<br /> at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:264)<br /> at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:292)<br /> at org.ops4j.util.xml.XmlUtils.parseDoc(XmlUtils.java:77)<br /> at org.ops4j.pax.runner.platform.internal.PlatformDefinitionImpl.&lt;init&gt;(PlatformDefinitionImpl.java:95)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.createPlatformDefinition(PlatformImpl.java:763)

---

**Fixed in:** 0.17.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Released as part of 0.17.0
