### ISSUE TITLE
Error with Spring DM 1.2.0-m2 and Pax:provision/runner 0.16 [PAXRUNNER-197]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#230]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** created **[PAXRUNNER-197](https://ops4j1.jira.com/browse/PAXRUNNER-197)** 

I have discovered a bug. When I try to deploy my Spring OSGI bundles using the maven command :

mvn org.ops4j:maven-pax-plugin:provision -Dprofiles=spring-dm

Pax returns the following error for Spring DM 1.2.0-m2 :

-&gt; Downloading bundles...

-&gt; Felix 1.4.0 : 365180 bytes `@` [ 80kBps ]

-&gt; org.osgi.compendium (4.1.0) : 514214 bytes `@` [ 82kBps ]

-&gt; org.ops4j.pax.logging.api : 76899 bytes `@` [ 30kBps ]

-&gt; org.ops4j.pax.logging.service : 425821 bytes `@` [ 98kBps ]]

-&gt; com.springsource.org.aopalliance : 4608 bytes `@` [ 4608kBps ]

-&gt; org.springframework.aop : 325863 bytes `@` [ 33kBps ]

-&gt; org.springframework.beans : 488038 bytes `@` [ 64kBps ]

-&gt; org.springframework.context : 476834 bytes `@` [ 42kBps ]]

-&gt; org.springframework.context.support : 117045 bytes `@` [ 47kBps ]

___

/ /

/ / Oops, there has been a problem!

/ /

/__/

___

/__/

-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support

is not a valid bundle

ava.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support](https://ops4j1.jira.com/wiki/display/mvn/org.springframework%2Fspring-support) is

not a valid bundle

at org.ops4j.pax.runner.Run.startPlatform(Run.java:472)

at org.ops4j.pax.runner.Run.start(Run.java:196)

at org.ops4j.pax.runner.Run.main(Run.java:646)

at org.ops4j.pax.runner.Run.main(Run.java:619)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

at java.lang.reflect.Method.invoke(Method.java:597)

at org.ops4j.pax.construct.lifecycle.ProvisionMojo.invokePaxRunner(ProvisionMojo.java:802)

at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployRunnerNG(ProvisionMojo.java:780)

at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployBundles(ProvisionMojo.java:477)

at org.ops4j.pax.construct.lifecycle.ProvisionMojo.execute(ProvisionMojo.java:270)

at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav

:330)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)

at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)

at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)

at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)

at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

at java.lang.reflect.Method.invoke(Method.java:597)

at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)

at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)

at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

aused by: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.springframework/spring-support](https://ops4j1.jira.com/wiki/display/mvn/org.springframework%2Fspring-support) is not a valid bund

e

at org.ops4j.pax.runner.platform.internal.PlatformImpl.validateBundleAndGetFilename(PlatformImpl.java:774)

at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:655)

at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:457)

at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadPlatformBundles(PlatformImpl.java:508)

at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:199)

at org.ops4j.pax.runner.Run.startPlatform(Run.java:468)

... 29 more

But everything works fine for the others Spring jars.

What is wrong ?

---

**Affects:** 0.16.0
**Fixed in:** 0.17.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[NiclasH](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd78a044-88d7-4a40-9764-d524ebec1713)** commented

Can you manually check if the spring-support jar can be loaded into the framework?



Also, what happen if you remove the spring-support from your local maven repository and try again? Perhaps it a corrupt download has happened.

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

Can you manually check if the spring-support jar can be loaded into the framework?



&gt;&gt; How can achieve this using pax ?



Also, what happen if you remove the spring-support from your local maven repository and try again? Perhaps it a corrupt download has happened.



&gt;&gt; My local maven copy of Spring jars are not used. The jat is downloaded by Pax through one of the following repository :



&lt;repository&gt;<br /> &lt;snapshots&gt;<br /> &lt;enabled&gt;false&lt;/enabled&gt;<br /> &lt;/snapshots&gt;<br /> &lt;id&gt;spring-milestones&lt;/id&gt;<br /> &lt;url&gt;[http://s3.amazonaws.com/maven.springframework.org/milestone](http://s3.amazonaws.com/maven.springframework.org/milestone)&lt;/url&gt;<br /> &lt;/repository&gt;<br /> &lt;repository&gt;<br /> &lt;snapshots /&gt;<br /> &lt;id&gt;spring-snapshots&lt;/id&gt;<br /> &lt;url&gt;[http://static.springframework.org/maven2-snapshots](http://static.springframework.org/maven2-snapshots)&lt;/url&gt;<br /> &lt;/repository&gt;

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

Additionaly, I see that the following command does not work anymore :



D:\Soft\opensource\pax\osgi&gt;pax-run --profiles=spring-dm<br /> ______ ________ __ __<br /> / __ / / __ / / / / /<br /> / ___/ / __ / _\ \ _/<br /> / / / / / / / _\ \ <br /> /_*/ /**/ /**/ /*/ /_/



Pax Runner (0.16.0) from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> -----------------------------------------------------



-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Using only arguments from command line<br /> -&gt; Provision from [spring-dm](https://ops4j1.jira.com/wiki/display/paxrunner/spring-dm)<br /> -&gt; Provision from [scan-dir:spring-dm](https://ops4j1.jira.com/wiki/display/scan-dir/spring-dm)<br /> ___<br /> / /<br /> / / Oops, there has been a problem!<br /> / /<br /> /__/<br /> ___<br /> /__/



-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.provision.MalformedSpecificationException: Specification [spring-dm<br /> ] could not be used<br /> java.lang.RuntimeException: org.ops4j.pax.runner.provision.MalformedSpecificationException: Specification [spring-dm](https://ops4j1.jira.com/wiki/display/paxrunner/spring-dm) co<br /> uld not be used<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:358)<br /> at org.ops4j.pax.runner.Run.start(Run.java:192)<br /> at org.ops4j.pax.runner.Run.main(Run.java:646)<br /> at org.ops4j.pax.runner.Run.main(Run.java:619)<br /> Caused by: org.ops4j.pax.runner.provision.MalformedSpecificationException: Specification [spring-dm](https://ops4j1.jira.com/wiki/display/paxrunner/spring-dm) could not be used<br /> at org.ops4j.pax.runner.scanner.dir.internal.DirScanner.scan(DirScanner.java:205)<br /> at org.ops4j.pax.runner.provision.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:163)<br /> at org.ops4j.pax.runner.provision.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:101)<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:348)<br /> ... 3 more

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

Forget my previous comment. The following command works using under windows "" characters :



pax-run "-~~profiles=spring-dm" "~~-log=INFO"

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

I can install the jar manually (even if I have another error) :



D:\Soft\opensource\pax\osgi\spring-test&gt;pax-run "scan-bundle:[file:spring-context-support-2.5.6.jar](file:spring-context-support-2.5.6.jar)"<br /> ______ ________ __ __<br /> / __ / / __ / / / / /<br /> / ___/ / __ / _\ \ _/<br /> / / / / / / / _\ \ <br /> /_*/ /**/ /**/ /*/ /_/



Pax Runner (0.16.0) from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> -----------------------------------------------------



-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Using only arguments from command line<br /> -&gt; Provision from [scan-bundle:file:spring-context-support-2.5.6.jar](https://ops4j1.jira.com/wiki/display/scan-bundle/file%3Aspring-context-support-2.5.6.jar)<br /> -&gt; Installing bundle [

 {location=file:spring-context-support-2.5.6.jar,startlevel=null,shouldStart=true,shouldUpdate=fal se} 

]<br /> -&gt; Using default executor<br /> -&gt; Downloading bundles...<br /> -&gt; org.apache.felix.shell (1.0.2) : 51390 bytes `@` [ 64kBps ]<br /> -&gt; org.apache.felix.shell.tui.plugin (1.0.2) : 12237 bytes `@` [ 48kBps ]<br /> -&gt; [file:spring-context-support-2.5.6.jar](file:spring-context-support-2.5.6.jar) : 96880 bytes `@` [ 1562kBps ]<br /> -&gt; Execution environment [J2SE-1.6](https://ops4j1.jira.com/wiki/display/paxrunner/J2SE-1.6)<br /> -&gt; Starting platform [Felix 1.4.0](https://ops4j1.jira.com/wiki/display/paxrunner/Felix+1.4.0). Runner has successfully finished his job!



Welcome to Felix.<br /> =================



-&gt; ERROR: Error starting [file:/D:/Soft/opensource/pax/osgi/spring-test/runner/bundles/org.springframework.context.suppor](file:/D:/Soft/opensource/pax/osgi/spring-test/runner/bundles/org.springframework.context.suppor)<br /> t_2.5.6.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle 1: package; (&amp;(package=org.apache.commo<br /> ns.logging)(version&gt;=1.0.4)(!(version&gt;=2.0.0))))<br /> org.osgi.framework.BundleException: Unresolved constraint in bundle 1: package; (&amp;(package=org.apache.commons.logging)(v<br /> ersion&gt;=1.0.4)(!(version&gt;=2.0.0)))<br /> at org.apache.felix.framework.Felix._resolveBundle(Felix.java:1775)<br /> at org.apache.felix.framework.Felix._startBundle(Felix.java:1635)<br /> at org.apache.felix.framework.Felix.startBundle(Felix.java:1578)<br /> at org.apache.felix.framework.Felix.setFrameworkStartLevel(Felix.java:1172)<br /> at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:265)<br /> at java.lang.Thread.run(Thread.java:619)<br /> ps<br /> START LEVEL 6<br /> ID State Level Name<br /> [ 0] [Active](https://ops4j1.jira.com/wiki/display/paxrunner/Active) [ 0] System Bundle (1.4.0)<br /> [ 1] [Installed](https://ops4j1.jira.com/wiki/display/paxrunner/Installed) [ 5] Spring Context Support (2.5.6)<br /> [ 2] [Active](https://ops4j1.jira.com/wiki/display/paxrunner/Active) [ 1] osgi.compendium (4.1.0.build-200702212030)<br /> [ 3] [Active](https://ops4j1.jira.com/wiki/display/paxrunner/Active) [ 1] Apache Felix Shell Service (1.0.2)<br /> [ 4] [Active](https://ops4j1.jira.com/wiki/display/paxrunner/Active) [ 1] Apache Felix Shell TUI (1.0.2)<br /> -&gt; start 1<br /> org.osgi.framework.BundleException: Unresolved constraint in bundle 1: package; (&amp;(package=org.apache.commons.logging)(v<br /> ersion&gt;=1.0.4)(!(version&gt;=2.0.0)))<br /> -&gt;

**Comment by ops4j-issues** [comment]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** commented

The following profile works :



D:\Soft\opensource\pax\spring-dm&gt;pax-run "--profiles=spring-dm-1.0.2"<br /> ______ ________ __ __<br /> / __ / / __ / / / / /<br /> / ___/ / __ / _\ \ _/<br /> / / / / / / / _\ \ <br /> /_*/ /**/ /**/ /*/ /_/



Pax Runner (0.16.0) from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> -----------------------------------------------------



-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Using only arguments from command line<br /> -&gt; Using default executor<br /> -&gt; Downloading bundles...<br /> -&gt; org.springframework.spring-aop : 323289 bytes `@` [ 2586kBps ]<br /> -&gt; org.springframework.spring-beans : 467331 bytes `@` [ 2976kBps ]<br /> -&gt; org.springframework.spring-context : 455159 bytes `@` [ 2646kBps ]<br /> -&gt; org.springframework.spring-core : 275073 bytes `@` [ 2957kBps ]<br /> -&gt; org.springframework.osgi.asm.osgi : 179276 bytes `@` [ 2298kBps ]<br /> -&gt; com.springsource.edu.emory.mathcs.backport : 331897 bytes `@` [ 55kBps ]<br /> -&gt; com.springsource.net.sf.cglib : 328786 bytes `@` [ 6995kBps ]]<br /> -&gt; org.springframework.osgi.spring-osgi-annotation : 16400 bytes `@` [ 16400kBps ]<br /> -&gt; org.springframework.osgi.spring-osgi-core : 248125 bytes `@` [ 5394kBps ]<br /> -&gt; org.springframework.osgi.spring-osgi-extender : 64890 bytes `@` [ 4326kBps ]<br /> -&gt; org.springframework.osgi.spring-osgi-io : 17943 bytes `@` [ 17943kBps ]<br /> -&gt; org.apache.felix.shell (1.0.2) : 51390 bytes `@` [ 117kBps ]<br /> -&gt; org.apache.felix.shell.tui.plugin (1.0.2) : 12237 bytes `@` [ 71kBps ]<br /> -&gt; Execution environment [J2SE-1.6](https://ops4j1.jira.com/wiki/display/paxrunner/J2SE-1.6)<br /> -&gt; Starting platform [Felix 1.4.0](https://ops4j1.jira.com/wiki/display/paxrunner/Felix+1.4.0). Runner has successfully finished his job!



So, I think that there is something wrong in Pax-runner 0.16.0 to work with Spring OSGI 1.2.0-m2 and spring framework 2.5.6

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Looks like the spring support jar is no longer required and should be eliminated from the profile. The latest version of spring-support is 2.0.8.<br /> I will do that and let you know.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Released as part of 0.17.0
