### ISSUE TITLE
Stackoverflow when cyclic dependencies in composites [PAXRUNNER-225]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#256]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** created **[PAXRUNNER-225](https://ops4j1.jira.com/browse/PAXRUNNER-225)** 

When composits refer to composits it can happen that a recursive invocation happens, resulting in a <br /> -&gt; java.lang.StackOverflowError<br /> java.lang.StackOverflowError<br /> at java.io.InputStream.&lt;init&gt;(InputStream.java:28)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:96)<br /> at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:66)<br /> at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:70)<br /> at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:161)<br /> at org.ops4j.net.URLUtils.prepareInputStream(URLUtils.java:134)<br /> at org.ops4j.pax.runner.scanner.composite.internal.CompositeScanner.scan(CompositeScanner.java:113)<br /> ..

To me, the composite reactor should track urls so that it does not "follow" a url twice (does not make sense also).

---

**Fixed in:** (none)
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

So, url should be graceful by default, printing a warn only in case of cyclic referals.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Even if it would be a nice to have I would not implement such a feature as it adds unnecessary complexity with to less benefits. The complexity is related to how you keep track of what is the current stack of scanners to avoid recursion.
