### ISSUE TITLE
web profile not wokring on KF [PAXRUNNER-28]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#27]
**[PeterN](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:1e605c61-aa05-45a0-abf9-a02bb2efc71b)** created **[PAXRUNNER-28](https://ops4j1.jira.com/browse/PAXRUNNER-28)** 

Seems some version hickup is preventing the web profile to start on KF, Equinox and Felix are working fine.

Shel output:

peter-mbp:~/code/ops4j/projects/pax/runner/runner peter$ ./pax-run --clean --platform=choose --profiles=web<br /> ______ ________ __ __<br /> / __ / / __ / / / / /<br /> / ___/ / __ / _\ \ _/<br /> / / / / / / / _\ \ <br /> /_*/ /**/ /**/ /*/ /_/

Pax Runner from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> --------------------------------------------

-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Protocol [mvn](https://ops4j1.jira.com/wiki/display/paxrunner/mvn) handler started<br /> -&gt; Protocol [wrap](https://ops4j1.jira.com/wiki/display/paxrunner/wrap) handler started<br /> -&gt; Scanner for schema [scan-bundle](https://ops4j1.jira.com/wiki/display/paxrunner/scan-bundle) started<br /> -&gt; Scanner for schema [scan-dir](https://ops4j1.jira.com/wiki/display/paxrunner/scan-dir) started<br /> -&gt; Scanner for schema [scan-file](https://ops4j1.jira.com/wiki/display/paxrunner/scan-file) started<br /> -&gt; Provision from [.!/*.jar](https://ops4j1.jira.com/wiki/display/paxrunner/.%21%2F*.jar)<br /> -&gt; Provision from [scan-dir:.!/*.jar](https://ops4j1.jira.com/wiki/display/scan-dir/.%21%2F*.jar)<br /> -&gt; your platform? kf<br /> -&gt; Downloading bundles...<br /> -&gt; Execution environment [J2SE-1.6](https://ops4j1.jira.com/wiki/display/paxrunner/J2SE-1.6)<br /> -&gt; Starting platform [Knopflerfish](https://ops4j1.jira.com/wiki/display/paxrunner/Knopflerfish). Runner has succesfully finished his job!<br /> Knopflerfish OSGi framework, version 4.0.0<br /> Copyright 2003-2006 Knopflerfish. All Rights Reserved.

See [http://www.knopflerfish.org](http://www.knopflerfish.org) for more information.<br /> Loading xargs url [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/knopflerfish/config.ini](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/knopflerfish/config.ini)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-1358612368.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-1358612368.bundle) (id#1)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-892341557.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-892341557.bundle) (id#2)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1034979817.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1034979817.bundle) (id#3)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-243284167.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-243284167.bundle) (id#4)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-1237112648.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-1237112648.bundle) (id#5)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/2138648037.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/2138648037.bundle) (id#6)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/985593455.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/985593455.bundle) (id#7)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-469489078.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/-469489078.bundle) (id#8)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1884038103.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1884038103.bundle) (id#9)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1124149689.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1124149689.bundle) (id#10)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1379336532.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/1379336532.bundle) (id#11)<br /> Installed and started: [file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/840817572.bundle](file:/Users/peter/code/ops4j/projects/pax/runner/runner/runner/bundles/840817572.bundle) (id#12)<br /> 0 [startlevel job thread](https://ops4j1.jira.com/wiki/display/paxrunner/startlevel+job+thread) INFO org.apache.commons.logging.internal.Activator - Enabling Jakarta Commons Logging API support.<br /> 6 [startlevel job thread](https://ops4j1.jira.com/wiki/display/paxrunner/startlevel+job+thread) INFO org.ops4j.pax.logging.slf4j.Aorg.osgi.framework.BundleException: Failed, missing package(s) or can not resolve all of the them: org.osgi.service.http;version=1.2.0<br /> at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:313)<br /> at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:279)<br /> at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:211)<br /> at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:172)<br /> at java.langctivator - Enabling SLF4J API support.<br /> #.Thread.run(Thread.java:613)

1. DEBUG: errors - FrameworkErrorEvent bundle #5 
   1. DEBUG: errors - FrameworkErrorEvent throwable:<br /> 17 [startlevel job thread](https://ops4j1.jira.com/wiki/display/paxrunner/startlevel+job+thread) INFO [undefined](https://ops4j1.jira.com/wiki/display/paxrunner/undefined) - Starting<br /> 34 [startlevel job thread](https://ops4j1.jira.com/wiki/display/paxrunner/startlevel+job+thread) INFO [undefined](https://ops4j1.jira.com/wiki/display/paxrunner/undefined) - Starting version 1.0.0<br /> &gt; Framework launched

\> lsb -1<br /> id level/state name<br /> --------------------<br /> 0 0/active System Bundle<br /> 1 5/active Pax Logging API<br /> 2 5/active Pax Logging Service<br /> 3 5/active Pax Logging JCL Support<br /> 4 5/active Pax Logging SLF4J Support<br /> 5 5/installed service [org.ops4j.pax.web.service](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.web.service)<br /> 6 5/active cm-API<br /> 7 5/active UserAdmin-API<br /> 8 5/active TTY-Console-IMPL<br /> 9 5/active FW-Commands-IMPL<br /> 10 5/active Console-IMPL<br /> 11 5/active Console-API<br /> 12 5/active LogCommands-IMPL<br /> &gt;

---

**Affects:** 0.5.0
**Fixed in:** 0.5.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

This is strange as the those are packages that makes up the sore specs.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Resolved by adding the wrapped org.osgi.compendium in the minimal profile (svn commit: r8444)
