### ISSUE TITLE
Pipe Closed When Generate Bundle [PAXRUNNER-244]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#273]
**[RuiT](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:49416563-777b-4aa1-b0ed-f6b639feadfa)** created **[PAXRUNNER-244](https://ops4j1.jira.com/browse/PAXRUNNER-244)** 

I'm trying Pax Runner 0.91.1 with Felix 1.6.1, But when I start my system, some exception occurred:

-&gt; wrap:[file:../lib/json-lib-2.2.3-jdk15.jar](file:../lib/json-lib-2.2.3-jdk15.jar) : downloading...<br /> -&gt; wrap:[file:../lib/json-lib-2.2.3-jdk15.jar](file:../lib/json-lib-2.2.3-jdk15.jar) : 150823 bytes `@` [ 1464kBps ]<br /> -&gt; wrap:[file:../lib/ezmorph-1.0.6.jar](file:../lib/ezmorph-1.0.6.jar) : downloading...<br /> -&gt; wrap:[file:../lib/ezmorph-1.0.6.jar](file:../lib/ezmorph-1.0.6.jar) : 87925 bytes `@` [ 1570kBps ]<br /> -&gt; [file:../lib/groovy-all-1.6.0.jar](file:../lib/groovy-all-1.6.0.jar) : downloading...<br /> Exception in thread "Thread-19" java.lang.RuntimeException: Bundle cannot be generated<br /> at org.ops4j.pax.url.bnd.BndUtils$1.run(BndUtils.java:144)<br /> Caused by: java.io.IOException: Pipe closed<br /> at java.io.PipedInputStream.checkStateForReceive(Unknown Source)<br /> at java.io.PipedInputStream.receive(Unknown Source)<br /> at java.io.PipedOutputStream.write(Unknown Source)<br /> at java.util.zip.ZipOutputStream.writeInt(Unknown Source)<br /> at java.util.zip.ZipOutputStream.writeCEN(Unknown Source)<br /> at java.util.zip.ZipOutputStream.finish(Unknown Source)<br /> at aQute.lib.osgi.Jar.write(Jar.java:214)<br /> at org.ops4j.pax.url.bnd.BndUtils$1.run(BndUtils.java:140)

I've created some config files to let pax runner download the bundle file<br /> (in my problem is groovy-all-1.6.0.jar) from local path (../lib from the<br /> current running folder) instead of the internet.

I've checked the source code ,it seems that when copy the bundle jar from<br /> my local path to bundle cache, piped stream is used, the exception throws<br /> when write the input stream to output stream. And the exception isn't always<br /> thrown when creating groovy bundles, but maybe some large bundle jar will do.

But after the exception, the system can start correctly, and the groovy<br /> bundle can work well. This matter won't happen when I use pax runner 0.17.2 with felix 1.4.1.

Attachment #1 pax-run.log<br /> Attachment #2 contains the following<br /> pax-run properties file<br /> custom platform definition<br /> default started bundles<br /> Attachment #3 is useless and has been contained in #2

---

**Affects:** 0.18.0, 0.19.0
**Fixed in:** 0.20.0
**Attachments:**
* [config.zip](https://ops4j1.jira.com/secure/attachment/10266/config.zip)
* [pax-run.log](https://ops4j1.jira.com/secure/attachment/10265/pax-run.log)
* [platform-definition.xml](https://ops4j1.jira.com/secure/attachment/10267/platform-definition.xml)

Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Unfortunately I cannot reproduce it. I used java 5 and java 6 on MacOs:



Pax Runner (0.20.0-SNAPSHOT) from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> --------------------------------------------------------------



-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Using only arguments from command line<br /> -&gt; Scan bundles from [wrap:file:groovy-all-1.6.0.jar](https://ops4j1.jira.com/wiki/display/wrap/file%3Agroovy-all-1.6.0.jar)<br /> -&gt; Scan bundles from [scan-bundle:wrap:file:groovy-all-1.6.0.jar](https://ops4j1.jira.com/wiki/display/scan-bundle/wrap%3Afile%3Agroovy-all-1.6.0.jar)<br /> -&gt; Provision bundle [wrap:file:groovy-all-1.6.0.jar, at default start level, bundle will be started, bundle will be loaded from the cache](https://ops4j1.jira.com/wiki/display/wrap/file%3Agroovy-all-1.6.0.jar%2C+at+default+start+level%2C+bundle+will+be+started%2C+bundle+will+be+loaded+from+the+cache)<br /> -&gt; Preparing framework [Felix 1.6.1](https://ops4j1.jira.com/wiki/display/paxrunner/Felix+1.6.1)<br /> -&gt; Downloading bundles...<br /> -&gt; Felix 1.6.1 : 365927 bytes `@` [ 228kBps ]<br /> -&gt; org.osgi.compendium (4.1.0) : 514214 bytes `@` [ 7044kBps ]<br /> -&gt; org.apache.felix.shell (1.2.0) : 59114 bytes `@` [ 87kBps ]<br /> -&gt; org.apache.felix.shell.tui.plugin (1.2.0) : 12455 bytes `@` [ 34kBps ]<br /> -&gt; wrap:[file:groovy-all-1.6.0.jar](file:groovy-all-1.6.0.jar) : 4392210 bytes `@` [ 3012kBps ]<br /> -&gt; Using execution environment [J2SE-1.6](https://ops4j1.jira.com/wiki/display/paxrunner/J2SE-1.6)<br /> -&gt; Runner has successfully finished his job!



Welcome to Felix.<br /> =================



-&gt;

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Maybe somebody with a Windows box can try to do this to figure out if it is related to windows or is about your specific setup.

**Comment by ops4j-issues** [comment]
**[RuiT](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:49416563-777b-4aa1-b0ed-f6b639feadfa)** commented

I'm deeply debugging this problem and find it has nothing to do with the groovy lib.



I think it may happen when the pax runner wraps the none bundle jars. I'm trying to describe my reproduce steps:



1. start up a new pax runner environment<br /> 2. use wrap feature to wrap an ordinary jar into a bundle<br /> 3. following the wrapped jar, you can put some big jars, like groovy<br /> 4. then restart the system



I think the problem should be reproduced.



In fact, the exception is thrown not because of generating the groovy bundle, but wrapping the ordinary jars, Since the wrapping process was running in a new thread, so the stack trace was just printed during download the BIG jar. I you follow the wrap with some other jars, the same thing will happen, but it makes you think PIPE CLOSED exception occurred unexpected.



Please try it out, thank you!

**Comment by ops4j-issues** [comment]
**[RuiT](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:49416563-777b-4aa1-b0ed-f6b639feadfa)** commented

I think I know where the problem is.



In the start properties, I add --autoWrap switch to make ordinary jars to be wrapped into bundles automatically.



But in the bundle list file (in the case is the system.bundles file), I add wrap:[file:../bundles/xxx.jar](file:../bundles/xxx.jar) to reference an ordinary jar. I've tried that if the wrap: prefixes omitted, everything works fine. No further pipe closed exceptions anymore.



So the problem is that if using --autoWrap switch, please DO NOT use wrap URL.



Is that right?

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Excellent tip. I could duplicate the problem. Working towards solving it.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Released as part of 0.2.0
