### ISSUE TITLE
Support for eclipse 3.5 (Galileo) builds [PAXRUNNER-265]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#290]
**[Hugues Malphettes](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:8b7dff3e-bad6-4d72-83b7-2097db6f3cb2)** created **[PAXRUNNER-265](https://ops4j1.jira.com/browse/PAXRUNNER-265)** 

Hi there.

I am trying to add support for the next version of eclipse: Galileo eclipse-3.5.

It seems the only things to change are inside the pax-runner-eclipse/pax-runner-eclipse-core fragment.

There are 2 API changes in the pde plugin. In the suggested fix I am using introspection to discover if the 3.4 or the 3.5 API should be used.<br /> If you don't mind having 2 versions of this fragment then the changes are a bit simpler.

The last change is to locate the built bundles.

With 3.5 when a new bundle is created, the version is by default 1.0.0.qualifier<br /> This string is processed specifically by pde to replace the qualifier by a timestamp.<br /> The suggested fix to be able to locate the bundle when it uses such version consists of looking at all the jars generated and selecting the most recent one that matches the bundle name we are looking for.

I am afraid that I have not been able to test those changes: I cannot find a 0.6.0-SNAPSHOT version of pax.url. I replaced it by a 0.5.2 version.<br /> I could not find either a version of pax.cache and so currently after my fixes, in eclipse-3.5-RC1 I know the bundles are exported and located but it fails with this trace (I inserted the e.printStackTrace() to get that trace):

java.lang.RuntimeException: Could not create [handler.cache](https://ops4j1.jira.com/wiki/display/paxrunner/handler.cache)<br /> at org.ops4j.pax.runner.Run.createActivator(Run.java:709)<br /> at org.ops4j.pax.runner.Run.installHandlers(Run.java:337)<br /> at org.ops4j.pax.runner.Run.start(Run.java:214)<br /> at org.ops4j.pax.runner.Run.main(Run.java:147)<br /> at org.ops4j.pax.cursor.LaunchConfiguration$1.run(LaunchConfiguration.java:233)<br /> at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:83)<br /> at org.eclipse.pde.ui.launcher.OSGiLaunchConfigurationDelegate.launch(OSGiLaunchConfigurationDelegate.java:43)<br /> at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:853)<br /> at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:703)<br /> at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:866)<br /> at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1069)<br /> at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)<br /> Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.url.cache.internal.Activator<br /> at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:489)

Let me know if you are interested by this contribution and if you let me know where I can locate the missing bundles, I'd be happy to test it further.<br /> Thanks.

---

**Affects:** 0.20.0
**Fixed in:** 1.0.0
**Attachments:**
* [PAXRUNNER-265-in-eclipse-3.4.1.png](https://ops4j1.jira.com/secure/attachment/10281/PAXRUNNER-265-in-eclipse-3.4.1.png)
* [PAXRUNNER-265-in-eclipse-3.5.png](https://ops4j1.jira.com/secure/attachment/10280/PAXRUNNER-265-in-eclipse-3.5.png)
* [pax-runner-eclipse_pax-runner-eclipse-core_src.diff](https://ops4j1.jira.com/secure/attachment/10279/pax-runner-eclipse_pax-runner-eclipse-core_src.diff)

Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

I'm very much interested in this contribution. So, please do not attach a patch but commit the changes directly to SVN. What is important is that the plugin still works then in 3.5 and the versions before.



Now back to your problem, for the moment the CI server does not work so the snapshots are not built, so you will have to also checkout Pax Url and build it using `mvn clean install`. Once this is done you will be able to build &amp; run Pax Runner and Eclipse plugin.

**Comment by ops4j-issues** [comment]
**[Hugues Malphettes](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:8b7dff3e-bad6-4d72-83b7-2097db6f3cb2)** commented

OK thanks for the hint.<br /> I was able to test end to end the changes in both versions of eclipse.<br /> I was not able to use the maven build. I am facing common exception when building from the command line:



[INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO) Failed to resolve artifact.



Couldn't find a version in [1.0.0-v20070423, 1.0.0-v20070606](https://ops4j1.jira.com/wiki/display/paxrunner/1.0.0-v20070423%2C+1.0.0-v20070606) to match range [1.0.0,2.0.0)<br /> org.eclipse.equinox:app:jar:null



from the specified remote repositories:<br /> central ([http://repo1.maven.org/maven2](http://repo1.maven.org/maven2)),<br /> eclipse.releases ([http://repo1.maven.org/eclipse](http://repo1.maven.org/eclipse)),<br /> ops4j.releases ([http://repository.ops4j.org/mvn-releases](http://repository.ops4j.org/mvn-releases))



Path to dependency:<br /> 1) org.ops4j.pax.runner:pax-runner-eclipse-core:jar:0.21.0-SNAPSHOT<br /> 2) org.eclipse.pde:ui:jar:3.3.0-v20070608-1300<br /> 3) org.eclipse.pde:core:jar:3.3.0-v20070608-1300<br /> 4) org.eclipse.core:runtime:jar:3.3.100-v20070530



[http://issues.apache.org/jira/browse/TUSCANY-2595](http://issues.apache.org/jira/browse/TUSCANY-2595)<br /> [http://www.opensubscriber.com/message/cactus-dev@jakarta.apache.org/9966113.html](http://www.opensubscriber.com/message/cactus-dev@jakarta.apache.org/9966113.html)



I committed the changes as advised.

**Comment by ops4j-issues** [comment]
**[Hugues Malphettes](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:8b7dff3e-bad6-4d72-83b7-2097db6f3cb2)** commented

Alin, my previous comment could be clearer:<br /> 1- The bug is fixed: I have successfully tested it on both eclipse 3.5 and 3.4 launching the plugin through eclipse-PDE.<br /> I have committed the code: [http://scm.ops4j.org/changelog/OPS4J?cs=15374](http://scm.ops4j.org/changelog/OPS4J?cs=15374)<br /> You can see it in the Fisheye tab of this bug. <br /> 2- I have some trouble building the plugin with maven.<br /> It is not your problem really.



Let me know if you want me to mark this bug as fixed or something else I can help with.<br /> Thanks!

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Excellent job. I will mark the issue as resolved.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Released as part of 1.0.0
