### ISSUE TITLE
Eclipse Plugin cannot launch bundle with "qualifier" in version [PAXRUNNER-291]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#314]
**[James Gula](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:6c69cb46-c8d3-43d8-b166-a32a186c1dcb)** created **[PAXRUNNER-291](https://ops4j1.jira.com/browse/PAXRUNNER-291)** 

Attempting to run a configuration for a bundle whose version is "1.0.0.qualifier" causes a null pointer induced by org.ops4j.pax.cursor.Utils.createBundleJars(Utils.java:534):

eclipse.buildId=I20090611-1540<br /> java.version=1.6.0_14<br /> java.vendor=Sun Microsystems Inc.<br /> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US<br /> Framework arguments: -product org.eclipse.epp.package.rcp.product<br /> Command-line arguments: -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

Error<br /> Thu Aug 13 22:03:27 PDT 2009<br /> An internal error occurred during: "Launching Hello".

java.lang.NullPointerException<br /> at java.lang.String.startsWith(String.java:1421)<br /> at java.lang.String.startsWith(String.java:1450)<br /> at org.ops4j.pax.cursor.Utils.createBundleJars(Utils.java:534)<br /> at org.ops4j.pax.cursor.Utils.getProvisioningFile(Utils.java:374)<br /> at org.ops4j.pax.cursor.LaunchConfiguration.getProgramArguments(LaunchConfiguration.java:161)<br /> at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:72)<br /> at org.eclipse.pde.ui.launcher.OSGiLaunchConfigurationDelegate.launch(OSGiLaunchConfigurationDelegate.java:43)<br /> at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:853)<br /> at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:703)<br /> at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:866)<br /> at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1069)<br /> at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Looking at createBundleJars, there is a loop trying to find the best jar matching a model that contains a clause f.getName().startsWith( bundleFileName ) when bundleFileName has not been initialized. Should this be something like: f.getName().startsWith( model.getPluginBase().getId() ) ?

Unfortunately Eclipse generates bundles with version in this form as its default. Changing the version to anything else like "1.0.0.foo" works around the problem.

---

**Affects:** 1.1.1
**Fixed in:** 1.2.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

I applied the suggested fix to get rid of NPE.

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Released as part of 1.2.0
