### ISSUE TITLE
scan-bundles does not find web bundles (*.war) [PAXRUNNER-319]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#337]
**[Michael Taeschner](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fc22b9b7-98f9-4897-b67e-eac92856920a)** created **[PAXRUNNER-319](https://ops4j1.jira.com/browse/PAXRUNNER-319)** 

We use the scan-composite approach to manage our application bundles for deployment. These include web-bundles with extension war. On "mvn pax:provision" Pax Runner cannot resolve the scan-bundle:mvn: ... path the the web-bundle.

Please allow web-bundles in composite scanning.

---

**Fixed in:** (none)
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

You will have to be more explicit like attaching the composite file (at least an example) and the error log or a description of what the problem is.

**Comment by ops4j-issues** [comment]
**[Michael Taeschner](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fc22b9b7-98f9-4897-b67e-eac92856920a)** commented

Within &lt;maven-repo&gt;/com/lhsystems/gsp/app/paymentProvider/webapp/1.0.0-SNAPSHOT/ the file **webapp-1.0.0-SNAPSHOT.war** is located, which is an web-bundle. With the following entry in my .composite file the exception below is thrown. If I rename the file to **webapp-1.0.0-SNAPSHOT.jar** everything works fine.



Composite Excerpt:



```java
...
scan-bundle:mvn:com.lhsystems.gsp.app.paymentProvider/webapp/1.0.0-SNAPSHOT
```



```java
>   Resolving metadata
>   Could not download [Version [1.0.0-20091015.152808-0] from URL [file:/C:/work/maven/com/lhsystems/gsp/app/paymentProvider/webapp/1.0.0-SNAPS

       ___
      /  /
     /  / Oops, there has been a problem!
    /  /
   /__/   URL [mvn:com.lhsystems.gsp.app.paymentProvider/webapp/1.0.0-SNAPSHOT] could not be resolved.
  ___
 /__/

> Exception catched during execution:
va.lang.RuntimeException: URL [mvn:com.lhsystems.gsp.app.paymentProvider/webapp/1.0.0-SNAPSHOT] could not be resolved.
      at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:195)
      at java.net.URL.openStream(URL.java:1007)
      at org.ops4j.pax.runner.platform.internal.StreamUtils.streamCopy(StreamUtils.java:112)
      at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:600)
      at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:390)
      at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:181)
      at org.ops4j.pax.runner.Run.startPlatform(Run.java:661)
      at org.ops4j.pax.runner.Run.start(Run.java:220)
      at org.ops4j.pax.runner.Run.main(Run.java:147)
      at org.ops4j.pax.runner.Run.main(Run.java:120)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
      at java.lang.reflect.Method.invoke(Method.java:585)
      at org.ops4j.pax.construct.lifecycle.ProvisionMojo.invokePaxRunner(ProvisionMojo.java:802)
      at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployRunnerNG(ProvisionMojo.java:780)
      at org.ops4j.pax.construct.lifecycle.ProvisionMojo.deployBundles(ProvisionMojo.java:477)
      at org.ops4j.pax.construct.lifecycle.ProvisionMojo.execute(ProvisionMojo.java:270)
      at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
      at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
      at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
      at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
      at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
      at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
      at java.lang.reflect.Method.invoke(Method.java:585)
      at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
      at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
      at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
      at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

**Comment by ops4j-issues** [comment]
**[Michael Taeschner](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fc22b9b7-98f9-4897-b67e-eac92856920a)** commented

On that occasion: could "&gt; Exception catched during execution:" be renamed to "&gt; Exception caught during execution:"

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

As you have to specify the &lt;type&gt; for a maven dependency, same is for the mvn url handler. You have to specify that is a jar. Read more: [http://wiki.ops4j.org//x/CoA6](http://wiki.ops4j.org//x/CoA6)



So, in your case:



```java
scan-bundle:mvn:com.lhsystems.gsp.app.paymentProvider/webapp/1.0.0-SNAPSHOT/war
```

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

I corrected the typos. Thanx.

**Comment by ops4j-issues** [comment]
**[Michael Taeschner](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fc22b9b7-98f9-4897-b67e-eac92856920a)** commented

Shame on me. Sorry, should have investigated this more thoroughly before ...
