### ISSUE TITLE
PAX DAEMON : pax-rund.sh --startd run failure with vmOptions [PAXRUNNER-334]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#350]
**[christophe](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:597fda63-34e0-4996-93ce-aae2a49f746c)** created **[PAXRUNNER-334](https://ops4j1.jira.com/browse/PAXRUNNER-334)** 

PAX-RUND.SH (PAX daemon launch command) does not work with the "--vmOptions" option, when this option contains several settings:<br /> =&gt; e.g.: PAX-RUND.SH --startd --vmOptions="-DMY_VAR1=var1" : works fine :smile:<br /> =&gt; e.g.: PAX-RUND.SH --startd --vmOptions="-DMY_VAR1=var1 MY_VAR2=var2" : fails !

Here is an example, obtained with PAXRUNNER 1.4.0 :

PAX-RUND.SH --startd --vmOptions="-Dhttp.proxyHost=xx.yy.zz.tt -Dhttp.proxyPort=pppp -DMY_VAR=/tmp" &lt;provision_file&gt;<br /> =&gt; fails with this exception :<br /> Exception in thread "RunnerLauncher" java.lang.RuntimeException: org.ops4j.pax.scanner.MalformedSpecificationException: Specification [-DMY_VAR=/tmp](https://ops4j1.jira.com/wiki/display/paxrunner/-DMY_VAR%3D%2Ftmp) could not be used<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:490)<br /> at org.ops4j.pax.runner.Run.start(Run.java:216)<br /> at org.ops4j.pax.runner.Run.main(Run.java:147)

While these same --vmOptions do work fine with the PAX-RUN command.<br /> This therefore appears to be a limitation related to the PAX-RUND --startd command...

Thanking you for any fix (or workaround) on this isssue.

Best Regards,

Christophe.

Nota: with (older) PAXRUNNER 1.1.0, the error obtained is different : PAX-RUND complains with:<br /> Exception in thread "RunnerLauncher" java.lang.RuntimeException: org.ops4j.pax.runner.provision.ScannerException: Could not parse the provision file<br /> =&gt; but the Exception obtained above with PAXRUNNER 1.4.0 looks more appropriate...

---

**Affects:** 1.4.0
Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[christophe](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:597fda63-34e0-4996-93ce-aae2a49f746c)** commented

For precision, moving the " character before the --vmOptions flag option, raises the same issue :<br /> e.g.: PAX-RUND.SH -~~startd "~~-vmOptions=-DMY_VAR1=var1 MY_VAR2=var2" &lt;provision_file&gt; : fails with the same exception !



While these same "--vmOptions=... ..." notation does work fine with the PAX-RUN command.

**Comment by ops4j-issues** [comment]
**[Niclas Hedhman](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:77912594-0a3e-4553-bb52-9b876d71537e)** commented

Shouldn't



--vmOptions="-DMY_VAR1=var1 MY_VAR2=var2"



be



--vmOptions="-DMY_VAR1=var1 -DMY_VAR2=var2"



??

**Comment by ops4j-issues** [comment]
**[Niclas Hedhman](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:77912594-0a3e-4553-bb52-9b876d71537e)** commented

Also, if you run in debug mode, you should see what it has interpreted the commandline as, just before launching the selected platform. A small report with vmOptions, classpath, platformOptions and other things are neatly output.

**Comment by ops4j-issues** [comment]
**[christophe](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:597fda63-34e0-4996-93ce-aae2a49f746c)** commented

Yes, I meant : --vmOptions="-DMY_VAR1=var1 -DMY_VAR2=var2"



But this is not working ; however, I found a way to make it work, doing this :<br /> PAX-RUND.SH --startd &lt;provision_file&gt;



With &lt;provision_file&gt; contents :<br /> [file:/path/to/bundle1/bundle1](file:/path/to/bundle1/bundle1)<br /> [file:/path/to/bundle2/bundle2](file:/path/to/bundle2/bundle2)<br /> ...<br /> -DMY_VAR1=var1<br /> -DMY_VAR2=var2



(instead of doing this :<br /> PAX-RUND.SH --startd --vmOptions="-DMY_VAR1=var1 -DMY_VAR2=var2" &lt;provision_file&gt;



With &lt;provision_file&gt; contents :<br /> [file:/path/to/bundle1/bundle1](file:/path/to/bundle1/bundle1)<br /> [file:/path/to/bundle2/bundle2](file:/path/to/bundle2/bundle2)<br /> ...<br /> )



=&gt; I would therefore suggest to move this defect to "Improvement" type (so that -vmOptions can be interpreted by PAX-RUND.SH like it is by PAX-RUN.SH)
