### ISSUE TITLE
Pax-Runner isn't able to load Profiles from osgi.sonatype.org [PAXRUNNER-338]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#354]
**[Former user](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ba7eaae4-09a2-439f-84ec-5bee28339264)** created **[PAXRUNNER-338](https://ops4j1.jira.com/browse/PAXRUNNER-338)** 

Pax Runner isn't able to resolve profile since on [http://osgi.sonatype.org/content/groups/pax-runner/org/ops4j/](http://osgi.sonatype.org/content/groups/pax-runner/org/ops4j/) aren't any profiles.

How could this happen?

C:\Windows&gt;pax-run "-~~profiles=compendium,event,ds" "~~-log=debug"<br /> __________ __________<br /> ______ _____ ___ ___ ______ __ __ ____ ____ ___________

\/ \/ \/ \/ \/ \/

Pax Runner (1.4.0) from OPS4J - [http://www.ops4j.org](http://www.ops4j.org)<br /> ----------------------------------------------------

-&gt; Using config [classpath:META-INF/runner.properties](https://ops4j1.jira.com/wiki/display/classpath/META-INF%2Frunner.properties)<br /> -&gt; Using only arguments from command line<br /> -&gt; Installing additional services<br /> -&gt; Installing service [service.obr](https://ops4j1.jira.com/wiki/display/paxrunner/service.obr)<br /> -&gt; Installing handlers<br /> -&gt; Handler [handler.mvn](https://ops4j1.jira.com/wiki/display/paxrunner/handler.mvn)<br /> -&gt; Handler for protocols [mvn](https://ops4j1.jira.com/wiki/display/paxrunner/mvn) started<br /> -&gt; Handler [handler.classpath](https://ops4j1.jira.com/wiki/display/paxrunner/handler.classpath)<br /> -&gt; Handler for protocols [classpath](https://ops4j1.jira.com/wiki/display/paxrunner/classpath) started<br /> -&gt; Handler [handler.war](https://ops4j1.jira.com/wiki/display/paxrunner/handler.war)<br /> -&gt; Handler for protocols [war, war-i, warref, webbundle](https://ops4j1.jira.com/wiki/display/paxrunner/war%2C+war-i%2C+warref%2C+webbundle) started<br /> -&gt; Handler [handler.wrap](https://ops4j1.jira.com/wiki/display/paxrunner/handler.wrap)<br /> -&gt; Handler for protocols [wrap](https://ops4j1.jira.com/wiki/display/paxrunner/wrap) started<br /> -&gt; Handler [handler.obr](https://ops4j1.jira.com/wiki/display/paxrunner/handler.obr)<br /> -&gt; Creating replaceable service for [interface org.osgi.service.obr.RepositoryAdmin](https://ops4j1.jira.com/wiki/display/paxrunner/interface+org.osgi.service.obr.RepositoryAdmin)<br /> -&gt; Creating service collection for [interface org.osgi.service.obr.RepositoryAdmin](https://ops4j1.jira.com/wiki/display/paxrunner/interface+org.osgi.service.obr.RepositoryAdmin)<br /> -&gt; Added service with reference [[org.osgi.service.obr.RepositoryAdmin](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.obr.RepositoryAdmin)]<br /> -&gt; Related service [org.apache.felix.bundlerepository.RepositoryAdminImpl@c51355](https://ops4j1.jira.com/wiki/display/paxrunner/org.apache.felix.bundlerepository.RepositoryAdminImpl%40c51355)<br /> -&gt; Service changed [null](https://ops4j1.jira.com/wiki/display/paxrunner/null) -&gt; [org.apache.felix.bundlerepository.RepositoryAdminImpl@c51355](https://ops4j1.jira.com/wiki/display/paxrunner/org.apache.felix.bundlerepository.RepositoryAdminImpl%40c51355)<br /> -&gt; Handler for protocols [obr](https://ops4j1.jira.com/wiki/display/paxrunner/obr) started<br /> -&gt; Handler [handler.link](https://ops4j1.jira.com/wiki/display/paxrunner/handler.link)<br /> -&gt; Handler for protocols [link](https://ops4j1.jira.com/wiki/display/paxrunner/link) started<br /> -&gt; Handler [handler.cache](https://ops4j1.jira.com/wiki/display/paxrunner/handler.cache)<br /> -&gt; Handler for protocols [cache](https://ops4j1.jira.com/wiki/display/paxrunner/cache) started<br /> -&gt; Handler [handler.assembly](https://ops4j1.jira.com/wiki/display/paxrunner/handler.assembly)<br /> -&gt; Handler for protocols [assembly, assemblyref](https://ops4j1.jira.com/wiki/display/paxrunner/assembly%2C+assemblyref) started<br /> -&gt; Handler [handler.dir](https://ops4j1.jira.com/wiki/display/paxrunner/handler.dir)<br /> -&gt; Handler for protocols [dir](https://ops4j1.jira.com/wiki/display/paxrunner/dir) started<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[cache](https://ops4j1.jira.com/wiki/display/paxrunner/cache)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@19fcc69](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%4019fcc69)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[mvn](https://ops4j1.jira.com/wiki/display/paxrunner/mvn)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@1bac748](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%401bac748)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[war, war-i, warref, webbundle](https://ops4j1.jira.com/wiki/display/paxrunner/war%2C+war-i%2C+warref%2C+webbundle)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@12f6684](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%4012f6684)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[obr](https://ops4j1.jira.com/wiki/display/paxrunner/obr)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@4b222f](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%404b222f)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[classpath](https://ops4j1.jira.com/wiki/display/paxrunner/classpath)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@1a457b6](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%401a457b6)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[dir](https://ops4j1.jira.com/wiki/display/paxrunner/dir)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@929206](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%40929206)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[assembly, assemblyref](https://ops4j1.jira.com/wiki/display/paxrunner/assembly%2C+assemblyref)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@ae000d](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%40ae000d)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[link](https://ops4j1.jira.com/wiki/display/paxrunner/link)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@169e11](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%40169e11)<br /> -&gt; URL stream handler service available [[org.osgi.service.url.URLStreamHandlerService](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.url.URLStreamHandlerService)]<br /> -&gt; Registering protocols [[wrap](https://ops4j1.jira.com/wiki/display/paxrunner/wrap)] to service [org.ops4j.pax.url.commons.handler.HandlerActivator$Handler@a39137](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.url.commons.handler.HandlerActivator%24Handler%40a39137)<br /> -&gt; URL stream handler service extender started<br /> -&gt; Installing provisioning<br /> -&gt; Scanner [scanner.bundle](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.bundle)<br /> -&gt; Scanner for schema [scan-bundle](https://ops4j1.jira.com/wiki/display/paxrunner/scan-bundle) started<br /> -&gt; Scanner [scanner.composite](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.composite)<br /> -&gt; Scanner for schema [scan-composite](https://ops4j1.jira.com/wiki/display/paxrunner/scan-composite) started<br /> -&gt; Scanner [scanner.dir](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.dir)<br /> -&gt; Scanner for schema [scan-dir](https://ops4j1.jira.com/wiki/display/paxrunner/scan-dir) started<br /> -&gt; Scanner [scanner.features](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.features)<br /> -&gt; Scanner for schema [scan-features](https://ops4j1.jira.com/wiki/display/paxrunner/scan-features) started<br /> -&gt; Scanner [scanner.file](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.file)<br /> -&gt; Scanner for schema [scan-file](https://ops4j1.jira.com/wiki/display/paxrunner/scan-file) started<br /> -&gt; Scanner [scanner.obr](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.obr)<br /> -&gt; Scanner for schema [scan-obr](https://ops4j1.jira.com/wiki/display/paxrunner/scan-obr) started<br /> -&gt; Scanner [scanner.pom](https://ops4j1.jira.com/wiki/display/paxrunner/scanner.pom)<br /> -&gt; Scanner for schema [scan-pom](https://ops4j1.jira.com/wiki/display/paxrunner/scan-pom) started<br /> -&gt; Start Level service available [[org.osgi.service.startlevel.StartLevel](https://ops4j1.jira.com/wiki/display/paxrunner/org.osgi.service.startlevel.StartLevel)]<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-features](https://ops4j1.jira.com/wiki/display/paxrunner/scan-features) from scanner [org.ops4j.pax.scanner.features.internal.FeaturesScanner@1a16869](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.features.internal.FeaturesScanner%401a16869)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-obr](https://ops4j1.jira.com/wiki/display/paxrunner/scan-obr) from scanner [org.ops4j.pax.scanner.obr.internal.ObrScanner@16f0472](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.obr.internal.ObrScanner%4016f0472)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-dir](https://ops4j1.jira.com/wiki/display/paxrunner/scan-dir) from scanner [org.ops4j.pax.scanner.dir.internal.DirScanner@360be0](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.dir.internal.DirScanner%40360be0)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-pom](https://ops4j1.jira.com/wiki/display/paxrunner/scan-pom) from scanner [org.ops4j.pax.scanner.pom.internal.PomScanner@1372a1a](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.pom.internal.PomScanner%401372a1a)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-file](https://ops4j1.jira.com/wiki/display/paxrunner/scan-file) from scanner [org.ops4j.pax.scanner.file.internal.FileScanner@126b249](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.file.internal.FileScanner%40126b249)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-bundle](https://ops4j1.jira.com/wiki/display/paxrunner/scan-bundle) from scanner [org.ops4j.pax.scanner.bundle.internal.BundleScanner@192d342](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.bundle.internal.BundleScanner%40192d342)<br /> -&gt; Scanner available [[org.ops4j.pax.scanner.Scanner](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.Scanner)]<br /> -&gt; Added scheme [scan-composite](https://ops4j1.jira.com/wiki/display/paxrunner/scan-composite) from scanner [org.ops4j.pax.scanner.composite.internal.CompositeScanner@1c78e57](https://ops4j1.jira.com/wiki/display/paxrunner/org.ops4j.pax.scanner.composite.internal.CompositeScanner%401c78e57)<br /> -&gt; Provisioning service started<br /> -&gt; Scan bundles from [scan-composite:mvn:org.ops4j.pax.runner.profiles/compendium//composite](https://ops4j1.jira.com/wiki/display/scan-composite/mvn%3Aorg.ops4j.pax.runner.profiles%2Fcompendium%2F%2Fcomposite)<br /> -&gt; Scanning [mvn:org.ops4j.pax.runner.profiles/compendium//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fcompendium%2F%2Fcomposite)<br /> -&gt; Resolving [mvn:org.ops4j.pax.runner.profiles/compendium//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fcompendium%2F%2Fcomposite)<br /> -&gt; Collecting versions from repository [file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true](file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true)<br /> -&gt; Resolving metadata<br /> -&gt; Skipping repository [file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true](file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true), reason: Metadata not found in repository [file:/C:/U<br /> sers/patbaumgartner/.m2/repository/]<br /> -&gt; Collecting versions from repository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false)<br /> -&gt; Resolving metadata<br /> -&gt; Skipping repository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false), reason: Metadata not found in re<br /> pository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/)<br /> -&gt; Collecting versions from repository [http://osgi.sonatype.org/content/groups/pax-runner/,releases=true,snapshots=false](http://osgi.sonatype.org/content/groups/pax-runner/,releases=true,snapshots=false)<br /> -&gt; Resolving metadata<br /> -&gt; Resolving latest version<br /> -&gt; Scan bundles from [scan-bundle:mvn:org.osgi/org.osgi.compendium/4.2.0](https://ops4j1.jira.com/wiki/display/scan-bundle/mvn%3Aorg.osgi%2Forg.osgi.compendium%2F4.2.0)<br /> -&gt; Scanning [mvn:org.osgi/org.osgi.compendium/4.2.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Forg.osgi.compendium%2F4.2.0)<br /> -&gt; Installing bundle [

 {location=mvn:org.osgi/org.osgi.compendium/4.2.0,startlevel=null,shouldStart=true,shouldUpdate=false} 

]<br /> -&gt; Installed bundle [mvn:org.osgi/org.osgi.compendium/4.2.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Forg.osgi.compendium%2F4.2.0)<br /> -&gt; Bundle [mvn:org.osgi/org.osgi.compendium/4.2.0](https://ops4j1.jira.com/wiki/display/mvn/org.osgi%2Forg.osgi.compendium%2F4.2.0) will be started<br /> -&gt; Scan bundles from [scan-composite:mvn:org.ops4j.pax.runner.profiles/event//composite](https://ops4j1.jira.com/wiki/display/scan-composite/mvn%3Aorg.ops4j.pax.runner.profiles%2Fevent%2F%2Fcomposite)<br /> -&gt; Scanning [mvn:org.ops4j.pax.runner.profiles/event//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fevent%2F%2Fcomposite)<br /> -&gt; Resolving [mvn:org.ops4j.pax.runner.profiles/event//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fevent%2F%2Fcomposite)<br /> -&gt; Collecting versions from repository [file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true](file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true)<br /> -&gt; Resolving metadata<br /> -&gt; Skipping repository [file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true](file:/C:/Users/patbaumgartner/.m2/repository/,releases=true,snapshots=true), reason: Metadata not found in repository [file:/C:/U<br /> sers/patbaumgartner/.m2/repository/]<br /> -&gt; Collecting versions from repository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false)<br /> -&gt; Resolving metadata<br /> -&gt; Skipping repository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/,releases=true,snapshots=false), reason: Metadata not found in re<br /> pository [http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/](http://scm.ops4j.org/repos/ops4j/projects/pax/runner-repository/)<br /> -&gt; Collecting versions from repository [http://osgi.sonatype.org/content/groups/pax-runner/,releases=true,snapshots=false](http://osgi.sonatype.org/content/groups/pax-runner/,releases=true,snapshots=false)<br /> -&gt; Resolving metadata<br /> -&gt; Resolving latest version<br /> -&gt; Could not download [Version [1.0.0](https://ops4j1.jira.com/wiki/display/paxrunner/1.0.0) from URL [http://osgi.sonatype.org/content/groups/pax-runner/org/ops4j/pax/runner/profiles/event/1.0.0/event-1.0.0<br /> .composite]]

___<br /> / /<br /> / / Oops, there has been a problem!<br /> / /<br /> /__/ URL [mvn:org.ops4j.pax.runner.profiles/event//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fevent%2F%2Fcomposite) could not be resolved.<br /> ___<br /> /__/

-&gt; Exception caught during execution:<br /> java.lang.RuntimeException: URL [mvn:org.ops4j.pax.runner.profiles/event//composite](https://ops4j1.jira.com/wiki/display/mvn/org.ops4j.pax.runner.profiles%2Fevent%2F%2Fcomposite) could not be resolved.<br /> at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:195)<br /> at java.net.URL.openStream(URL.java:1010)<br /> at org.ops4j.pax.url.cache.internal.Connection.getInputStream(Connection.java:174)<br /> at org.ops4j.net.URLUtils.prepareInputStream(URLUtils.java:134)<br /> at org.ops4j.pax.scanner.composite.internal.CompositeScanner.scan(CompositeScanner.java:113)<br /> at org.ops4j.pax.scanner.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:154)<br /> at org.ops4j.pax.scanner.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:92)<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:469)<br /> at org.ops4j.pax.runner.Run.start(Run.java:216)<br /> at org.ops4j.pax.runner.Run.main(Run.java:147)<br /> at org.ops4j.pax.runner.Run.main(Run.java:120)

C:\Windows&gt;

---

**Affects:** 1.4.0
**Fixed in:** 1.4.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Former user](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ba7eaae4-09a2-439f-84ec-5bee28339264)** commented

SCM was accessible through https but not through http. Pax-Runner got some profiles from osgi.sonatype.org (proxy). Thats why some profile worked and some not. Toni helped to investigate and Niclas made the repo accessible with read rights for http. Everything works now fine! Thanks!
