### ISSUE TITLE
Eclipse plugin broken on Eclipse 3.6 (Helios) [PAXRUNNER-353]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#368]
**[Pieter](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:22092d66-c57b-422e-81bf-cee8306d4c2a)** created **[PAXRUNNER-353](https://ops4j1.jira.com/browse/PAXRUNNER-353)** 

Apparently internal packages have been reshuffled in the newest Eclipse version, like the org.eclipse.pde.internal.ui packages.<br /> The class org.eclipse.jdt.internal.ui.text.JavaBreakIterator.Run seems to have disappeared.

---

Votes: 3, Watches: 2

**Comment by ops4j-issues** [comment]
**[Christian Baranowski](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:58ab12c2-d0ce-41e6-bd39-346974727e4c)** commented

Today I created a Github fork with a fixed pax runner eclipse plugin which runs under Eclipse PDE 3.6.1 (Eclipse Helios). I would be very happy when the fork will be merged back into the pax runner git repo...



see [https://github.com/tux2323/org.ops4j.pax.runner/tree/master/pax-runner-eclipse](https://github.com/tux2323/org.ops4j.pax.runner/tree/master/pax-runner-eclipse)



There is also a tmp Eclipse Update Site to install a snapshot Pax Runner Eclipse Plugin Version into Eclipse Helios Update Site: [http://tux2323.github.com/pax-runner-update-site/](http://tux2323.github.com/pax-runner-update-site/)

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

Great. But, just trying myself, got (on mac):



[WARNING](https://ops4j1.jira.com/wiki/display/paxrunner/WARNING) Could not read bundle entry /Users/tonit/.m2/repository/p2/osgi/bundle/com.ibm.icu/4.2.1.v20100412/com.ibm.icu-4.2.1.v20100412.jar!/icu-data.jar<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO) Resolving target platform for project MavenProject: org.ops4j.pax.runner:org.ops4j.pax.runner.eclipse.updatesite:1.7.5-SNAPSHOT `@` /Users/tonit/devel/oss/org.ops4j.pax.runner/pax-runner-eclipse/pax-runner-eclipse-updatesite/pom.xml<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO) Adding repository (cached) [http://download.eclipse.org/releases/helios](http://download.eclipse.org/releases/helios)<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO) Cannot complete the request. Generating details.<br /> [INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO)

 {org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1, osgi.ws=cocoa, osgi.arch=x86_64, osgi.os=macosx, org.eclipse.update.install.features=true, org.osgi.framework.system.packages=} 

[INFO](https://ops4j1.jira.com/wiki/display/paxrunner/INFO) [Software being installed: org.ops4j.pax.runner.eclipse.updatesite raw:1.7.5.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S](https://ops4j1.jira.com/wiki/display/paxrunner/-S)]]):1.7.5-SNAPSHOT, Missing requirement: org.ops4j.pax.runner.eclipse.updatesite raw:1.7.5.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S](https://ops4j1.jira.com/wiki/display/paxrunner/-S)]]):1.7.5-SNAPSHOT requires 'org.ops4j.pax.runner.eclipse.ui.feature.feature.group [1.7.5,1.7.6)' but it could not be found](https://ops4j1.jira.com/wiki/display/paxrunner/1.7.5%2C1.7.6%29%27+but+it+could+not+be+found)<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable. -&gt; [Help 1](https://ops4j1.jira.com/wiki/display/paxrunner/Help+1)<br /> org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)<br /> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)<br /> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)<br /> at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)<br /> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)<br /> Caused by: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.<br /> at org.eclipse.tycho.p2.impl.resolver.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:102)<br /> at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveProject(P2ResolverImpl.java:324)<br /> at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveProject(P2ResolverImpl.java:293)<br /> at org.eclipse.tycho.p2.facade.P2TargetPlatformResolver.doResolvePlatform(P2TargetPlatformResolver.java:389)<br /> at org.eclipse.tycho.p2.facade.P2TargetPlatformResolver.resolvePlatform(P2TargetPlatformResolver.java:150)<br /> at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:90)<br /> at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:91)<br /> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:273)<br /> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)<br /> ... 11 more<br /> Caused by: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.<br /> ... 20 more<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) <br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) To see the full stack trace of the errors, re-run Maven with the -e switch.<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) Re-run Maven using the -X switch to enable full debug logging.<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) <br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) For more information about the errors and possible solutions, please read the following articles:<br /> [ERROR](https://ops4j1.jira.com/wiki/display/paxrunner/ERROR) [Help 1](https://ops4j1.jira.com/wiki/display/paxrunner/Help+1) [http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException](http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException)<br /> zazu:pax-runner-eclipse tonit$



Looking into it, but i'm a noob in Tycho, yet.

**Comment by ops4j-issues** [comment]
**[Christian Baranowski](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:58ab12c2-d0ce-41e6-bd39-346974727e4c)** commented

I also build the project on Mac OSX with no build error.



I use Maven Version 3.0.3 with a clean local repository nothing in it. Here my steps how I have build the project successful:



1.) Install the Pax Runner Snapshot Version 1.7.5-SNAPSHOT with<br /> mvn clean install



2.) Run the Maven Build in the eclipse plugin project with (pax-runner-eclipse)<br /> mvn clean install



My Java Version is: 1.6.0_26



I have no idea what went wrong on your mac :slightly_frowning_face: <br /> Did you use maven 3? Tycho need maven version &gt;= 3

**Comment by ops4j-issues** [comment]
**[Toni Menzel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:e7e50a9b-1dd6-45df-b446-7b0e65306e2b)** commented

Sure Maven 3.0.3.<br /> Will give it a fresh run asap.



Thanks for heads up!

**Comment by ops4j-issues** [comment]
**[Kostas Giannoutakis](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:4f1eda14-d7c9-48cf-96d4-79939378d943)** commented

Hi, how can I build this version of pax runner within eclipse?
