### ISSUE TITLE
pax-runner with pax:provision [PAXRUNNER-432]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#433]
**[Paul Vonnahme](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:395bd8c3-8faf-4c53-a999-70cb336a8ee5)** created **[PAXRUNNER-432](https://ops4j1.jira.com/browse/PAXRUNNER-432)** 

I've just started trying to do some things with OSGI. A couple weeks ago I had used pax-create-project to creating an OSGI project, and pax:provision was working. It broke last week, and I noticed the new version of pax-runner (1.8.5) had been released. I switched back to 1.8.3 by adding &lt;runner&gt;1.8.3&lt;/runner&gt; to my maven-pax-plugin configuration and it works again. If I download [https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.ops4j.pax.runner&a=pax-runner-assembly&v=1.8.5&e=zip&c=jdk15](https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.ops4j.pax.runner&a=pax-runner-assembly&v=1.8.5&e=zip&c=jdk15) and unzip it I'm able to use 1.8.5, so it must be something with the archetype and pax:provision that leads to my error.

The error I get with 1.8.5 but not with 1.8.3 when using pax:provision on the archetype is:

```
 -> Preparing framework [Felix 4.0.3]
 -> Downloading bundles...
 -> Using execution environment [J2SE-1.6]
 -> Runner has successfully finished his job!

java.lang.NoClassDefFoundError: releases
Caused by: java.lang.ClassNotFoundException: releases
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: releases.  Program will exit.
Exception in thread "main"
 -> Platform has been shutdown.
```

This is minor since I can use 1.8.3, and it may be an issue with my environment since I'm new to this, but thought I would report it in case others are having the same issue.

---

Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Dmytro Pishchukhin](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:75d4dbcd-6ce7-4eba-bea7-c784ab506ce1)** commented

Could you provide pax-runner options you use, please?
