### ISSUE TITLE
java.lang.AbstractMethodError/ClassCastException when creating integration test for osgi using felix and PaxRunner Framework [PAXRUNNER-443]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#440]
**[Aldrin Tingson](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b0ebe0f5-63ee-40c2-8b22-247729596f02)** created **[PAXRUNNER-443](https://ops4j1.jira.com/browse/PAXRUNNER-443)** 

I am trying to create integration test for my bundle. basically I want to mimic the setup I have in normal web app project(wherein the test are in src/test folder)

I am almost there except that I have exception when the bundle tries to activate

***native container exception***

Running com.grundfos.wcm.impl.HelloWorldServiceImplIntegrationTest<br /> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.196 sec &lt;&lt;&lt; FAILURE! - in com.grundfos.wcm.impl.HelloWorldServiceImplIntegrationTest<br /> whenSuppliedNullNameThenThrowException(com.grundfos.wcm.impl.HelloWorldServiceImplIntegrationTest) Time elapsed: 0.792 sec &lt;&lt;&lt; ERROR!<br /> java.lang.AbstractMethodError: org.apache.felix.framework.BundleImpl.adapt(Ljava/lang/Class;)Ljava/lang/Object; at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:311)<br /> at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:177)<br /> at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)<br /> at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:264)<br /> at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)<br /> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)<br /> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)<br /> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)<br /> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)<br /> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)<br /> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)<br /> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)<br /> at org.junit.runners.ParentRunner.run(ParentRunner.java:236)<br /> at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)<br /> at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)<br /> at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)<br /> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)<br /> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

***forked container exception***

java.lang.ClassCastException: org.ops4j.pax.exam.inject.internal.Activator cannot be cast to org.osgi.framework.BundleActivator<br /> at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:3814)<br /> at org.apache.felix.framework.Felix.activateBundle(Felix.java:1899)<br /> at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)<br /> at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)<br /> at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)<br /> at java.lang.Thread.run(Thread.java:745)<br /> java.lang.ClassCastException: org.ops4j.pax.exam.raw.extender.intern.Activator cannot be cast to org.osgi.framework.BundleActivator

Can someone expert help me with my problem? I am at the end of my ropes already :slightly_frowning_face:

Sample Project(If the project file does not work just tell me):

git clone git`@bitbucket`.org:aldrintingson/cq-training.git

commands:

mvn clean verify

Fix propsed:<br /> 1. Make sure that org.osgi.core has a provided scope

in the parent project it is provided already, plus i tried explicitly specifying it in pom.xml of the bundle(core folder) and still no avail.

2. Create a package first of the project then bundle then add it to bundles during the Configuration phase

did the following steps:

a. uncommented out this line of code in HelloWorldServiceImplIntegrationTest.java<br /> //bundle("file:target/cq-training-core-1.0-SNAPSHOT.jar"),

b. mvn clean package -DskipTests<br /> c. mvn verify

same error

Thanks

---

Votes: 1, Watches: 3

**Comment by ops4j-issues** [comment]
**[Benson Margulies](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:20d18d91-8fe0-40c1-8e3b-d984d492a5a4)** commented

Here's what I see:



```
ERROR: Bundle org.ops4j.pax.logging.pax-logging-api [5] Error starting link:classpath:META-INF/links/org.ops4j.pax.logging.api.link (org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.logging.pax-logging-api [5].)
java.lang.ClassCastException: org.ops4j.pax.logging.internal.Activator cannot be cast to org.osgi.framework.BundleActivator
	at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4362)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
```



Here's my relevant dependency:



```
org.osgi:org.osgi.core:jar:5.0.0:provided
```



Here's my test setup. The bundles in here include nothing from pax, it's all my stuff.



```java
 return options(
                provision(bundles),
                // add in the root when we are using the root case.
                when(useRootFragment()).useOptions(url(String.format("file:%s/rbl-osgi-%s-fragment-bundle.jar", projectBuildDirectory, projectVersion)).noStart()),
                systemPackages(
                        // These are needed for guava.
                        "sun.misc",
                        "javax.annotation",
                        // actually used in RBL; perhaps we need to eliminate?
                        "javax.swing.text",
                        //
                        String.format("org.slf4j;version=\"%s\"", getDependencyVersion("org.slf4j", "slf4j-api"))

                ),
                junitBundles(),
                systemProperty("org.ops4j.pax.logging.DefaultServiceLog.level").value("WARN")
        );
```
