### ISSUE TITLE
Jar contains ops4j artifacts, causes java.lang.AbstractMethodError in pax-runner [PAXRUNNER-450]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#445]
**[Ioan Eugen Stan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a5551a1c-5e2c-4f72-bd05-e9353cf41703)** created **[PAXRUNNER-450](https://ops4j1.jira.com/browse/PAXRUNNER-450)** 

I've made some dependency upgrades to pax-runner so I can provision karaf features. One dependency was pax-url from 1.x to 2.2.0 . The build passes but the artifact is unusable. When run I get this:

-------------------<br /> ___<br /> / /<br /> / / Oops, there has been a problem!<br /> / /<br /> /__/ org.ops4j.pax.url.mvn.internal.Activator$1.createConfiguration(Lorg/ops4j/util/property/PropertyResolver;)Ljava/lang/Object;<br /> ___<br /> /__/

-&gt; Exception caught during execution:<br /> java.lang.AbstractMethodError: org.ops4j.pax.url.mvn.internal.Activator$1.createConfiguration(Lorg/ops4j/util/property/PropertyResolver;)Ljava/lang/Object;<br /> at org.ops4j.pax.url.commons.handler.HandlerActivator.start(HandlerActivator.java:122)<br /> at org.ops4j.pax.runner.Run.createActivator(Run.java:754)<br /> at org.ops4j.pax.runner.Run.installHandlers(Run.java:353)<br /> at org.ops4j.pax.runner.Run.start(Run.java:201)<br /> at org.ops4j.pax.runner.Run.main(Run.java:134)<br /> at org.ops4j.pax.runner.Run.main(Run.java:102)<br /> ----------------

The issue seems to be related to shading. The anonymous inner lass in org.ops4j.pax.url.mvn.internal.Activator has a createConfigurationMethod that receives an org.ops4j.util.property.PropertyResolver type object. However. the MavenConfigurationImpl class is expecting a shaded version: shaded.org.ops4j.util.property.PropertyResolver

---

final MavenConfigurationImpl config =<br /> new MavenConfigurationImpl( propertyResolver, ServiceConstants.PID );

---

---

**Affects:** 1.8.6
Votes: 0, Watches: 2

---
**Referenced issues**

**aggregation of:**
* #196 - Upgrade to pax-url 2.3.0 [PAXRUNNER-449]

**blocks:**
* #195 - Upgrade to pax-url 2.2.0 [PAXRUNNER-446]

**Comment by ops4j-issues** [comment]
**[Mario Krizmanić](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:f8b110f4-c26b-4de3-b7d0-1384d20229ba)** commented

Please test with pax-runner 1.8.7-SNAPSHOT
