### ISSUE TITLE
--workingDirectory does not work as expected [PAXRUNNER-46]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#67]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXRUNNER-46](https://ops4j1.jira.com/browse/PAXRUNNER-46)** 

The following bug should be addressed (from David Leangen):

-&gt; Searching for [workingDirectory=/home/runtime/](https://ops4j1.jira.com/wiki/display/paxrunner/workingDirectory%3D%2Fhome%2Fruntime%2F)<br /> -&gt; Specification is not a valid url: no protocol:<br /> workingDirectory=/home/runtime/. Continue discovery...<br /> -&gt; Specification is not a valid file. Continue discovery...<br /> -&gt; Specification is not a valid zip file. Stopping.<br /> ___<br /> / /<br /> / / Ops, there has been a problem!<br /> / /<br /> /__/<br /> ___<br /> /__/

-&gt; java.lang.RuntimeException:<br /> org.ops4j.pax.runner.provision.MalformedSpecificationException:<br /> Specification [workingDirectory=/home/runtime/](https://ops4j1.jira.com/wiki/display/paxrunner/workingDirectory%3D%2Fhome%2Fruntime%2F) could not be used<br /> java.lang.RuntimeException:<br /> org.ops4j.pax.runner.provision.MalformedSpecificationException:<br /> Specification [workingDirectory=/home/runtime/](https://ops4j1.jira.com/wiki/display/paxrunner/workingDirectory%3D%2Fhome%2Fruntime%2F) could not be used<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:286)<br /> at org.ops4j.pax.runner.Run.start(Run.java:139)<br /> at org.ops4j.pax.runner.Run.main(Run.java:473)<br /> Caused by:<br /> org.ops4j.pax.runner.provision.MalformedSpecificationException:<br /> Specification [workingDirectory=/home/runtime/](https://ops4j1.jira.com/wiki/display/paxrunner/workingDirectory%3D%2Fhome%2Fruntime%2F) could not be used<br /> at<br /> org.ops4j.pax.runner.scanner.dir.internal.DirScanner.scan(DirScanner.java:181)<br /> at<br /> org.ops4j.pax.runner.provision.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:159)<br /> at<br /> org.ops4j.pax.runner.provision.internal.ProvisionServiceImpl.scan(ProvisionServiceImpl.java:101)<br /> at org.ops4j.pax.runner.Run.installBundles(Run.java:276)<br /> ... 2 more

---

**Affects:** 0.5.0
**Fixed in:** 0.5.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Teste and works okay.<br /> Looking at the trace it looks like the workingDirectory option did not had – in front of so it was considered an provisioning url not an option.
