### ISSUE TITLE
Equinox CM bundle could not be downloaded (404 error) [PAXRUNNER-140]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#73]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** created **[PAXRUNNER-140](https://ops4j1.jira.com/browse/PAXRUNNER-140)** 

-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar](http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar) could not be downloaded<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar](http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar) could not be downloaded<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:433)<br /> at org.ops4j.pax.runner.Run.start(Run.java:156)<br /> at org.ops4j.pax.runner.Run.main(Run.java:545)<br /> at org.ops4j.pax.runner.Run.main(Run.java:518)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException: [http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar](http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar) could not be downloaded<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:562)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:399)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadPlatformBundles(PlatformImpl.java:450)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:191)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:429)<br /> ... 3 more<br /> Caused by: java.io.FileNotFoundException: [http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar](http://download.eclipse.org/eclipse/equinox/drops/I20080328-1410/org.eclipse.equinox.cm_1.0.0.v20080310.jar)<br /> at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1239)<br /> at java.net.URL.openStream(URL.java:1009)<br /> at org.ops4j.pax.runner.platform.internal.StreamUtils.streamCopy(StreamUtils.java:105)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:549)

---

**Affects:** 0.9.0
**Fixed in:** 0.10.0
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** commented

This works:



[http://www.eclipse.org/downloads/download.php?file=/eclipse/equinox/drops/R-3.3.2-200802211800/org.eclipse.equinox.cm_3.2.0.v20070116.jar](http://www.eclipse.org/downloads/download.php?file=/eclipse/equinox/drops/R-3.3.2-200802211800/org.eclipse.equinox.cm_3.2.0.v20070116.jar)

**Comment by ops4j-issues** [comment]
**[Hendy Irawan](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0d210b36-5d07-43fe-97f6-31159abdaec5)** commented

Newer one:



[http://www.eclipse.org/downloads/download.php?file=/eclipse/equinox/drops/S-3.4RC1-200805161333/org.eclipse.equinox.cm_1.0.0.v20080509-1800.jar](http://www.eclipse.org/downloads/download.php?file=/eclipse/equinox/drops/S-3.4RC1-200805161333/org.eclipse.equinox.cm_1.0.0.v20080509-1800.jar)

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

After some more "research" on how eclipse keeps the artifacts, the "I" drops are form integration builds and they are not very long lived, hence why the artifact cannot be found anymore as the integration builds are removed after a while.<br /> But the "R" drops are released that are kept for a long period, as (I hope) the "S" releases for RC (release candidates).<br /> For now I used the RC2 drops, in cm case teh link being: [http://download.eclipse.org/eclipse/equinox/drops/S-3.4RC2-200805230100/org.eclipse.equinox.cm_1.0.0.v20080509-1800.jar](http://download.eclipse.org/eclipse/equinox/drops/S-3.4RC2-200805230100/org.eclipse.equinox.cm_1.0.0.v20080509-1800.jar)



As soon as eclipse 3.4 will be released we will use the "R" drops also for cm/ds artifacts.
