### ISSUE TITLE
"workingDirectory" option broken on linux [PAXRUNNER-50]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#74]
**[David Leangen](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:51aa7020-bc9c-4e10-bb9f-bc5a45225f5b)** created **[PAXRUNNER-50](https://ops4j1.jira.com/browse/PAXRUNNER-50)** 

The "workingDirectory" option is broken on Linux.

For instance, using the following command:

./pax-run.sh "--workingDirectory=/home/runtime/temp/"

Pax Runner returns an error:

___<br /> / /<br /> / / Ops, there has been a problem!<br /> / /<br /> /__/<br /> ___<br /> /__/

-&gt; java.lang.RuntimeException:<br /> org.ops4j.pax.runner.platform.PlatformException:<br /> [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be<br /> downloaded<br /> java.lang.RuntimeException:<br /> org.ops4j.pax.runner.platform.PlatformException:<br /> [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be<br /> downloaded<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:378)<br /> at org.ops4j.pax.runner.Run.start(Run.java:143)<br /> at org.ops4j.pax.runner.Run.main(Run.java:473)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException:<br /> [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be<br /> downloaded<br /> at<br /> org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:463)<br /> at<br /> org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadSystemFile(PlatformImpl.java:401)<br /> at<br /> org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:172)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:374)<br /> ... 2 more<br /> Caused by: java.io.IOException: No such file or directory<br /> at java.io.UnixFileSystem.createFileExclusively(Native Method)<br /> at java.io.File.createNewFile(File.java:850)<br /> at<br /> org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:445)<br /> ... 5 more

---

**Fixed in:** (none)
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[David Leangen](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:51aa7020-bc9c-4e10-bb9f-bc5a45225f5b)** commented

Could be related to this issue:



In the above example, I noticed that a directory "true" is being created in the current working directory, while nothing gets created in "workingDirectory".

**Comment by ops4j-issues** [comment]
**[David Leangen](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:51aa7020-bc9c-4e10-bb9f-bc5a45225f5b)** commented

User error.



See: [http://issues.ops4j.org/jira/browse/PAXRUNNER-51](http://issues.ops4j.org/jira/browse/PAXRUNNER-51)
