### ISSUE TITLE
Output better errors when permissions are not met to work on a directory [PAXRUNNER-51]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#76]
**[David Leangen](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:51aa7020-bc9c-4e10-bb9f-bc5a45225f5b)** created **[PAXRUNNER-51](https://ops4j1.jira.com/browse/PAXRUNNER-51)** 

Due to an oversight as a user, I tried to use the --workingDirectory option on a directory for which I did not have adequate permissions. However, an error was thrown by the system:

-&gt; java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be downloaded<br /> java.lang.RuntimeException: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be downloaded<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:378)<br /> at org.ops4j.pax.runner.Run.start(Run.java:143)<br /> at org.ops4j.pax.runner.Run.main(Run.java:473)<br /> Caused by: org.ops4j.pax.runner.platform.PlatformException: [mvn:org.apache.felix/org.apache.felix.main/1.0.0](https://ops4j1.jira.com/wiki/display/mvn/org.apache.felix%2Forg.apache.felix.main%2F1.0.0) could not be downloaded<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:463)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadSystemFile(PlatformImpl.java:401)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:172)<br /> at org.ops4j.pax.runner.Run.startPlatform(Run.java:374)<br /> ... 2 more<br /> Caused by: java.io.IOException: No such file or directory<br /> at java.io.UnixFileSystem.createFileExclusively(Native Method)<br /> at java.io.File.createNewFile(File.java:850)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:445)

It would be helpful to output a more informative error. Perhaps we can first check for permissions, and if they are not adequate, output a user-friendly error to that effect.

---

Votes: 0, Watches: 1

**Comment by ops4j-issues** [comment]
**[NiclasH](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd78a044-88d7-4a40-9764-d524ebec1713)** commented

We can't really check for permissions at file system level in Java. So it need to be deduced indirectly, and possibly only provide suggestion of what could be wrong.

**Comment by ops4j-issues** [comment]
**[David Leangen](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:51aa7020-bc9c-4e10-bb9f-bc5a45225f5b)** commented

Issue is outdated.
