### ISSUE TITLE
Error is thrown when maven local repository directory does not exist [PAXRUNNER-58]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#82]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** created **[PAXRUNNER-58](https://ops4j1.jira.com/browse/PAXRUNNER-58)** 

When runner is started and the local repository does not exist an error is thrown indicating that there is no protocol (see bellow). The "c" is from the path to user home repository which on windows is usually on "C:\..."

Caused by: java.net.MalformedURLException: unknown protocol: c<br /> at java.net.URL.&lt;init&gt;(URL.java:574)<br /> at java.net.URL.&lt;init&gt;(URL.java:464)<br /> at java.net.URL.&lt;init&gt;(URL.java:413)<br /> at org.ops4j.pax.runner.handler.mvn.internal.ConfigurationImpl.getLocalRepository(ConfigurationImpl.java:234)<br /> at org.ops4j.pax.runner.handler.mvn.internal.ConfigurationImpl.getRepositories(ConfigurationImpl.java:181)<br /> at org.ops4j.pax.runner.handler.mvn.internal.Connection.getInputStream(Connection.java:131)<br /> at java.net.URL.openStream(URL.java:1007)<br /> at org.ops4j.pax.runner.platform.internal.StreamUtils.streamCopy(StreamUtils.java:123)<br /> at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:451)<br /> ... 5 more

---

**Affects:** 0.5.0
**Fixed in:** 0.5.1
Votes: 0, Watches: 0

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

No exceptions are thrown anymore if localRepo or settings.xml cannot be resolved. <br /> Just log as warning and try to go further.<br /> This will allow to use runner also on a system that has not maven at all.
