### ISSUE TITLE
Occasional corrupted text in pax-runner console output [PAXRUNNER-68]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.runner#92]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** created **[PAXRUNNER-68](https://ops4j1.jira.com/browse/PAXRUNNER-68)** 

from Jason Anderson via email (jla415 at gmail)<br /> ==============================================

Hi All,

is there any way to get stop pax-runner from outputting multiple sets<br /> of output to the console at the same time? here is an example of one<br /> of the less severe cases:

org.osgi.framework.BundleException: Bundle symbolic name and version<br /> are not unique.<br /> at org.apache.felix.framework.Felix.createModule(Felix.java:3321)<br /> at org.apache.felix.framework.Felix.createBundleInfo(Felix.java:3262)<br /> at org.apache.felix.framework.Felix.installBundle(Felix.java:2223)<br /> at org.apache.felix.framework.Felix.installBundle(Felix.java:2137)<br /> at org.apache.felix.framework.Felix.processAutoProperties(Felix.java:3652)<br /> at org.apache.felix.framework.Felix.start(Felix.java:802)<br /> EatR RoOrRg.:a pAauchteo.-fperloipxe.rmtaiiens.<br /> Mianisnt.amlali.n ((Moarign..ojsagvia.:f1r9a5m)e<br /> work.BundleException: Could not create bundle object.)<br /> org.osgi.framework.BundleException: Bundle symbolic name and version<br /> are not unique.<br /> at org.apache.felix.framework.Felix.createModule(Felix.java:3321)<br /> at org.apache.felix.framework.Felix.createBundleInfo(Felix.java:3262)<br /> at org.apache.felix.framework.Felix.installBundle(Felix.java:2223)<br /> at org.apache.felix.framework.Felix.installBundle(Felix.java:2137)<br /> at org.apache.felix.framework.Felix.processAutoProperties(Felix.java:3684)<br /> at org.apache.felix.framework.Felix.start(Felix.java:802)<br /> at org.apache.felix.main.Main.main(Main.java:195)

if you look in the middle between the 2 exceptions there's another<br /> line of text being written to the console at the same time (something<br /> along the lines of ERROR: Auto-properties start.<br /> (org.osgi.framework.BundleException:...))

in the most severe cases I've seen it have screens and screens of text<br /> interspersed like this with no way to tell exactly what is written

it makes it hard to debug my bundle files if i cant read the<br /> exceptions that occur so any help would be appreciated

pax-runner 0.5.2

java version "1.5.0_07"<br /> Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_07-164)<br /> Java HotSpot(TM) Client VM (build 1.5.0_07-87, mixed mode, sharing)

Thanks!<br /> Jason

---

**Affects:** 0.5.2
**Fixed in:** 0.5.3
**Attachments:**
* [org.example.text.zip](https://ops4j1.jira.com/secure/attachment/10132/org.example.text.zip)

Votes: 0, Watches: 0

---
**Referenced issues**

**relates to:**
* #50 - Runner interfaces with prompts from platform console/tui bundles [PAXRUNNER-80]

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

should be just a matter of getting Pipe.java to use line-buffering so it only<br /> writes out text when it has a complete line (or when the Pipe is shut down<br /> in case the process terminates mid-stream)



at the moment the Pipe writes out each character at a time, so there's<br /> no line-level locking to stop the 'err' and 'out' streams from mixing text

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

sample testcase

**Comment by ops4j-issues** [comment]
**[Alin Dreghiciu](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a786db11-2013-41fb-af1d-ca5eb8f74aa0)** commented

Handle reading/writing using buffered readers/writers instead of buffered input/output streams.



Yet, I'm not sure if this solves the problem as I cannot reproduce it. I used the example provided by Stuart (thanx) but on windows at least everything was looking fine.

**Comment by ops4j-issues** [comment]
**[Stuart McCulloch](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bd0ce3b1-43d9-4c98-bd33-19159ea83eb1)** commented

fix resolves the problem seen on Linux
